// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITIS_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        sext_ln103,
        layer2_out_address0,
        layer2_out_ce0,
        layer2_out_q0,
        grp_fu_187_p_din0,
        grp_fu_187_p_dout0,
        grp_fu_187_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [31:0] m_axi_gmem_0_WDATA;
output  [3:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [31:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [8:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [61:0] sext_ln103;
output  [13:0] layer2_out_address0;
output   layer2_out_ce0;
input  [7:0] layer2_out_q0;
output  [31:0] grp_fu_187_p_din0;
input  [31:0] grp_fu_187_p_dout0;
output   grp_fu_187_p_ce;

reg ap_idle;
reg m_axi_gmem_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln110_2_reg_1044;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter14_reg;
reg   [0:0] icmp_ln109_1_reg_1048;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter14_reg;
reg   [0:0] icmp_ln108_1_reg_1052;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter14_reg;
reg    ap_predicate_op190_write_state16;
reg    ap_block_state16_io_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln103_fu_271_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [16:0] fc_w_address0;
wire  signed [7:0] fc_w_q0;
wire   [3:0] fc_b_address0;
wire   [11:0] fc_b_q0;
reg    gmem_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] icmp_ln103_reg_943;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln108_fu_303_p2;
reg   [0:0] icmp_ln108_reg_947;
reg   [0:0] icmp_ln108_reg_947_pp0_iter2_reg;
wire   [0:0] xor_ln103_fu_309_p2;
reg   [0:0] xor_ln103_reg_959;
wire   [0:0] icmp_ln109_fu_315_p2;
reg   [0:0] icmp_ln109_reg_964;
wire   [0:0] and_ln103_1_fu_321_p2;
reg   [0:0] and_ln103_1_reg_969;
reg   [0:0] and_ln103_1_reg_969_pp0_iter2_reg;
wire   [3:0] select_ln103_4_fu_327_p3;
reg   [3:0] select_ln103_4_reg_980;
reg   [3:0] select_ln103_4_reg_980_pp0_iter2_reg;
reg   [3:0] select_ln103_4_reg_980_pp0_iter3_reg;
reg   [3:0] select_ln103_4_reg_980_pp0_iter4_reg;
reg   [3:0] select_ln103_4_reg_980_pp0_iter5_reg;
wire   [0:0] empty_fu_335_p2;
reg   [0:0] empty_reg_985;
wire   [0:0] first_iter_9_mid2_fu_456_p3;
reg   [0:0] first_iter_9_mid2_reg_995;
reg   [0:0] first_iter_9_mid2_reg_995_pp0_iter3_reg;
reg   [0:0] first_iter_9_mid2_reg_995_pp0_iter4_reg;
reg   [0:0] first_iter_9_mid2_reg_995_pp0_iter5_reg;
reg   [0:0] first_iter_9_mid2_reg_995_pp0_iter6_reg;
wire   [0:0] icmp_ln110_mid2205_fu_478_p2;
reg   [0:0] icmp_ln110_mid2205_reg_1000;
wire   [4:0] select_ln108_1_fu_484_p3;
reg   [4:0] select_ln108_1_reg_1006;
wire   [4:0] x_2_mid2_fu_507_p3;
reg   [4:0] x_2_mid2_reg_1013;
reg   [4:0] x_2_mid2_reg_1013_pp0_iter3_reg;
wire   [4:0] select_ln109_1_fu_529_p3;
reg   [4:0] select_ln109_1_reg_1019;
wire   [0:0] and_ln110_fu_543_p2;
reg   [0:0] and_ln110_reg_1025;
reg   [0:0] and_ln110_reg_1025_pp0_iter3_reg;
reg   [0:0] and_ln110_reg_1025_pp0_iter4_reg;
reg   [0:0] and_ln110_reg_1025_pp0_iter5_reg;
reg   [0:0] and_ln110_reg_1025_pp0_iter6_reg;
wire   [9:0] add_ln112_fu_657_p2;
reg   [9:0] add_ln112_reg_1029;
wire   [8:0] trunc_ln112_fu_663_p1;
reg   [8:0] trunc_ln112_reg_1034;
wire   [0:0] icmp_ln110_2_fu_682_p2;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter4_reg;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter5_reg;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter6_reg;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter7_reg;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter8_reg;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter9_reg;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter10_reg;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter11_reg;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter12_reg;
reg   [0:0] icmp_ln110_2_reg_1044_pp0_iter13_reg;
wire   [0:0] icmp_ln109_1_fu_694_p2;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter4_reg;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter5_reg;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter6_reg;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter7_reg;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter8_reg;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter9_reg;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter10_reg;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter11_reg;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter12_reg;
reg   [0:0] icmp_ln109_1_reg_1048_pp0_iter13_reg;
wire   [0:0] icmp_ln108_1_fu_705_p2;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter4_reg;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter5_reg;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter6_reg;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter7_reg;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter8_reg;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter9_reg;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter10_reg;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter11_reg;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter12_reg;
reg   [0:0] icmp_ln108_1_reg_1052_pp0_iter13_reg;
wire  signed [31:0] grp_fu_839_p3;
reg  signed [31:0] sum_7_reg_1086;
wire   [31:0] bitcast_ln122_fu_820_p1;
reg   [31:0] bitcast_ln122_reg_1091;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln112_4_fu_773_p1;
wire   [63:0] zext_ln114_fu_778_p1;
wire   [63:0] zext_ln103_fu_790_p1;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [4:0] x_fu_106;
wire   [4:0] add_ln110_1_fu_677_p2;
reg   [4:0] ap_sig_allocacmp_x_load;
wire    ap_loop_init;
reg   [13:0] flat_idx_1_fu_110;
wire   [13:0] add_ln117_fu_671_p2;
reg   [13:0] add_ln108_119_fu_114;
wire   [13:0] add_ln108_1_fu_699_p2;
reg   [13:0] flat_idx_fu_118;
wire   [13:0] select_ln109_fu_623_p3;
reg   [13:0] add_ln11021_fu_122;
wire   [13:0] add_ln110_fu_688_p2;
reg   [4:0] y_fu_126;
reg   [9:0] indvar_flatten186_fu_130;
wire   [9:0] select_ln109_2_fu_351_p3;
reg   [4:0] c_fu_134;
reg   [13:0] indvars_iv136_fu_138;
wire   [13:0] select_ln108_fu_609_p3;
reg   [14:0] indvar_flatten206_fu_142;
wire   [14:0] select_ln108_3_fu_365_p3;
reg   [3:0] i_fu_146;
reg   [16:0] indvar_flatten238_fu_150;
wire   [16:0] add_ln103_1_fu_277_p2;
reg   [16:0] ap_sig_allocacmp_indvar_flatten238_load;
wire    ap_block_pp0_stage0;
reg   [31:0] sum_5_fu_154;
wire   [31:0] select_ln108_2_fu_801_p3;
reg   [31:0] ap_sig_allocacmp_sum_5_load;
reg  signed [31:0] ap_sig_allocacmp_sum_5_load_1;
reg    layer2_out_ce0_local;
reg    fc_w_ce0_local;
reg    fc_b_ce0_local;
wire   [3:0] add_ln103_fu_297_p2;
wire   [9:0] add_ln109_1_fu_345_p2;
wire   [14:0] add_ln108_2_fu_359_p2;
wire   [0:0] first_iter_9303_fu_404_p2;
wire   [0:0] first_iter_8306_fu_415_p2;
wire   [0:0] icmp_ln110_fu_426_p2;
wire   [4:0] select_ln103_1_fu_397_p3;
wire   [4:0] add_ln108_fu_437_p2;
wire   [0:0] first_iter_9_mid1_fu_450_p2;
wire   [0:0] or_ln103_fu_410_p2;
wire   [0:0] or_ln103_1_fu_421_p2;
wire   [0:0] exitcond_flatten188_not_fu_468_p2;
wire   [0:0] and_ln103_fu_432_p2;
wire   [0:0] not_exitcond_flatten188_mid2237_fu_473_p2;
wire   [4:0] y_5_mid2195_fu_443_p3;
wire   [0:0] empty_26_fu_497_p2;
wire   [0:0] empty_27_fu_502_p2;
wire   [4:0] add_ln109_fu_491_p2;
wire   [0:0] first_iter_8_mid1_fu_515_p2;
wire   [0:0] first_iter_8_mid2203_fu_463_p2;
wire   [0:0] first_iter_8_mid2_fu_521_p3;
wire   [0:0] icmp_ln110_1_fu_537_p2;
wire   [13:0] select_ln103_2_fu_581_p3;
wire   [13:0] select_ln103_3_fu_588_p3;
wire   [13:0] select_ln103_fu_574_p3;
wire   [13:0] flat_idx_1_mid2199_fu_602_p3;
wire   [13:0] flat_idx_mid2194_fu_595_p3;
wire   [6:0] tmp_fu_637_p3;
wire   [9:0] p_shl_fu_630_p3;
wire   [9:0] zext_ln112_fu_644_p1;
wire   [9:0] sub_ln112_fu_648_p2;
wire   [9:0] zext_ln112_1_fu_654_p1;
wire   [13:0] flat_idx_1_mid2_fu_616_p3;
wire   [11:0] tmp_62_fu_740_p3;
wire   [13:0] tmp_63_fu_747_p3;
wire   [13:0] zext_ln112_2_fu_754_p1;
wire   [13:0] sub_ln110_fu_758_p2;
wire   [13:0] zext_ln112_3_fu_764_p1;
wire   [13:0] add_ln112_1_fu_767_p2;
wire   [16:0] grp_fu_830_p3;
wire  signed [31:0] sext_ln104_fu_797_p1;
wire   [13:0] grp_fu_830_p0;
wire   [3:0] grp_fu_830_p1;
wire   [13:0] grp_fu_830_p2;
reg    grp_fu_211_ce;
reg    grp_fu_830_ce;
reg    grp_fu_839_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [16:0] grp_fu_830_p10;
wire   [16:0] grp_fu_830_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 x_fu_106 = 5'd0;
#0 flat_idx_1_fu_110 = 14'd0;
#0 add_ln108_119_fu_114 = 14'd0;
#0 flat_idx_fu_118 = 14'd0;
#0 add_ln11021_fu_122 = 14'd0;
#0 y_fu_126 = 5'd0;
#0 indvar_flatten186_fu_130 = 10'd0;
#0 c_fu_134 = 5'd0;
#0 indvars_iv136_fu_138 = 14'd0;
#0 indvar_flatten206_fu_142 = 15'd0;
#0 i_fu_146 = 4'd0;
#0 indvar_flatten238_fu_150 = 17'd0;
#0 sum_5_fu_154 = 32'd0;
#0 ap_done_reg = 1'b0;
end

dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITfYi #(
    .DataWidth( 8 ),
    .AddressRange( 125440 ),
    .AddressWidth( 17 ))
fc_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc_w_address0),
    .ce0(fc_w_ce0_local),
    .q0(fc_w_q0)
);

dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITg8j #(
    .DataWidth( 12 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
fc_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc_b_address0),
    .ce0(fc_b_ce0_local),
    .q0(fc_b_q0)
);

dense_int8_mac_muladd_14ns_4ns_14ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 17 ))
mac_muladd_14ns_4ns_14ns_17_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_830_p0),
    .din1(grp_fu_830_p1),
    .din2(grp_fu_830_p2),
    .ce(grp_fu_830_ce),
    .dout(grp_fu_830_p3)
);

dense_int8_mac_muladd_8s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_4_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(fc_w_q0),
    .din1(layer2_out_q0),
    .din2(ap_sig_allocacmp_sum_5_load_1),
    .ce(grp_fu_839_ce),
    .dout(grp_fu_839_p3)
);

dense_int8_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter14_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            c_fu_134 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            c_fu_134 <= select_ln108_1_fu_484_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            flat_idx_1_fu_110 <= 14'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            flat_idx_1_fu_110 <= add_ln117_fu_671_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            flat_idx_fu_118 <= 14'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            flat_idx_fu_118 <= select_ln109_fu_623_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_146 <= 4'd0;
        end else if (((icmp_ln103_reg_943 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_146 <= select_ln103_4_fu_327_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten186_fu_130 <= 10'd0;
        end else if (((icmp_ln103_reg_943 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten186_fu_130 <= select_ln109_2_fu_351_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten206_fu_142 <= 15'd0;
        end else if (((icmp_ln103_reg_943 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten206_fu_142 <= select_ln108_3_fu_365_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln103_fu_271_p2 == 1'd0))) begin
            indvar_flatten238_fu_150 <= add_ln103_1_fu_277_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten238_fu_150 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvars_iv136_fu_138 <= 14'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            indvars_iv136_fu_138 <= select_ln108_fu_609_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'd1 == and_ln110_reg_1025_pp0_iter6_reg))) begin
            sum_5_fu_154 <= select_ln108_2_fu_801_p3;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            sum_5_fu_154 <= grp_fu_839_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_fu_106 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            x_fu_106 <= add_ln110_1_fu_677_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_fu_126 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            y_fu_126 <= select_ln109_1_fu_529_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        add_ln108_119_fu_114 <= add_ln108_1_fu_699_p2;
        add_ln11021_fu_122 <= add_ln110_fu_688_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln112_reg_1029 <= add_ln112_fu_657_p2;
        and_ln103_1_reg_969_pp0_iter2_reg <= and_ln103_1_reg_969;
        and_ln110_reg_1025 <= and_ln110_fu_543_p2;
        and_ln110_reg_1025_pp0_iter3_reg <= and_ln110_reg_1025;
        and_ln110_reg_1025_pp0_iter4_reg <= and_ln110_reg_1025_pp0_iter3_reg;
        and_ln110_reg_1025_pp0_iter5_reg <= and_ln110_reg_1025_pp0_iter4_reg;
        and_ln110_reg_1025_pp0_iter6_reg <= and_ln110_reg_1025_pp0_iter5_reg;
        bitcast_ln122_reg_1091 <= bitcast_ln122_fu_820_p1;
        first_iter_9_mid2_reg_995 <= first_iter_9_mid2_fu_456_p3;
        first_iter_9_mid2_reg_995_pp0_iter3_reg <= first_iter_9_mid2_reg_995;
        first_iter_9_mid2_reg_995_pp0_iter4_reg <= first_iter_9_mid2_reg_995_pp0_iter3_reg;
        first_iter_9_mid2_reg_995_pp0_iter5_reg <= first_iter_9_mid2_reg_995_pp0_iter4_reg;
        first_iter_9_mid2_reg_995_pp0_iter6_reg <= first_iter_9_mid2_reg_995_pp0_iter5_reg;
        icmp_ln108_1_reg_1052 <= icmp_ln108_1_fu_705_p2;
        icmp_ln108_1_reg_1052_pp0_iter10_reg <= icmp_ln108_1_reg_1052_pp0_iter9_reg;
        icmp_ln108_1_reg_1052_pp0_iter11_reg <= icmp_ln108_1_reg_1052_pp0_iter10_reg;
        icmp_ln108_1_reg_1052_pp0_iter12_reg <= icmp_ln108_1_reg_1052_pp0_iter11_reg;
        icmp_ln108_1_reg_1052_pp0_iter13_reg <= icmp_ln108_1_reg_1052_pp0_iter12_reg;
        icmp_ln108_1_reg_1052_pp0_iter14_reg <= icmp_ln108_1_reg_1052_pp0_iter13_reg;
        icmp_ln108_1_reg_1052_pp0_iter4_reg <= icmp_ln108_1_reg_1052;
        icmp_ln108_1_reg_1052_pp0_iter5_reg <= icmp_ln108_1_reg_1052_pp0_iter4_reg;
        icmp_ln108_1_reg_1052_pp0_iter6_reg <= icmp_ln108_1_reg_1052_pp0_iter5_reg;
        icmp_ln108_1_reg_1052_pp0_iter7_reg <= icmp_ln108_1_reg_1052_pp0_iter6_reg;
        icmp_ln108_1_reg_1052_pp0_iter8_reg <= icmp_ln108_1_reg_1052_pp0_iter7_reg;
        icmp_ln108_1_reg_1052_pp0_iter9_reg <= icmp_ln108_1_reg_1052_pp0_iter8_reg;
        icmp_ln108_reg_947_pp0_iter2_reg <= icmp_ln108_reg_947;
        icmp_ln109_1_reg_1048 <= icmp_ln109_1_fu_694_p2;
        icmp_ln109_1_reg_1048_pp0_iter10_reg <= icmp_ln109_1_reg_1048_pp0_iter9_reg;
        icmp_ln109_1_reg_1048_pp0_iter11_reg <= icmp_ln109_1_reg_1048_pp0_iter10_reg;
        icmp_ln109_1_reg_1048_pp0_iter12_reg <= icmp_ln109_1_reg_1048_pp0_iter11_reg;
        icmp_ln109_1_reg_1048_pp0_iter13_reg <= icmp_ln109_1_reg_1048_pp0_iter12_reg;
        icmp_ln109_1_reg_1048_pp0_iter14_reg <= icmp_ln109_1_reg_1048_pp0_iter13_reg;
        icmp_ln109_1_reg_1048_pp0_iter4_reg <= icmp_ln109_1_reg_1048;
        icmp_ln109_1_reg_1048_pp0_iter5_reg <= icmp_ln109_1_reg_1048_pp0_iter4_reg;
        icmp_ln109_1_reg_1048_pp0_iter6_reg <= icmp_ln109_1_reg_1048_pp0_iter5_reg;
        icmp_ln109_1_reg_1048_pp0_iter7_reg <= icmp_ln109_1_reg_1048_pp0_iter6_reg;
        icmp_ln109_1_reg_1048_pp0_iter8_reg <= icmp_ln109_1_reg_1048_pp0_iter7_reg;
        icmp_ln109_1_reg_1048_pp0_iter9_reg <= icmp_ln109_1_reg_1048_pp0_iter8_reg;
        icmp_ln110_2_reg_1044 <= icmp_ln110_2_fu_682_p2;
        icmp_ln110_2_reg_1044_pp0_iter10_reg <= icmp_ln110_2_reg_1044_pp0_iter9_reg;
        icmp_ln110_2_reg_1044_pp0_iter11_reg <= icmp_ln110_2_reg_1044_pp0_iter10_reg;
        icmp_ln110_2_reg_1044_pp0_iter12_reg <= icmp_ln110_2_reg_1044_pp0_iter11_reg;
        icmp_ln110_2_reg_1044_pp0_iter13_reg <= icmp_ln110_2_reg_1044_pp0_iter12_reg;
        icmp_ln110_2_reg_1044_pp0_iter14_reg <= icmp_ln110_2_reg_1044_pp0_iter13_reg;
        icmp_ln110_2_reg_1044_pp0_iter4_reg <= icmp_ln110_2_reg_1044;
        icmp_ln110_2_reg_1044_pp0_iter5_reg <= icmp_ln110_2_reg_1044_pp0_iter4_reg;
        icmp_ln110_2_reg_1044_pp0_iter6_reg <= icmp_ln110_2_reg_1044_pp0_iter5_reg;
        icmp_ln110_2_reg_1044_pp0_iter7_reg <= icmp_ln110_2_reg_1044_pp0_iter6_reg;
        icmp_ln110_2_reg_1044_pp0_iter8_reg <= icmp_ln110_2_reg_1044_pp0_iter7_reg;
        icmp_ln110_2_reg_1044_pp0_iter9_reg <= icmp_ln110_2_reg_1044_pp0_iter8_reg;
        icmp_ln110_mid2205_reg_1000 <= icmp_ln110_mid2205_fu_478_p2;
        select_ln103_4_reg_980_pp0_iter2_reg <= select_ln103_4_reg_980;
        select_ln103_4_reg_980_pp0_iter3_reg <= select_ln103_4_reg_980_pp0_iter2_reg;
        select_ln103_4_reg_980_pp0_iter4_reg <= select_ln103_4_reg_980_pp0_iter3_reg;
        select_ln103_4_reg_980_pp0_iter5_reg <= select_ln103_4_reg_980_pp0_iter4_reg;
        select_ln108_1_reg_1006 <= select_ln108_1_fu_484_p3;
        select_ln109_1_reg_1019 <= select_ln109_1_fu_529_p3;
        trunc_ln112_reg_1034 <= trunc_ln112_fu_663_p1;
        x_2_mid2_reg_1013 <= x_2_mid2_fu_507_p3;
        x_2_mid2_reg_1013_pp0_iter3_reg <= x_2_mid2_reg_1013;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        and_ln103_1_reg_969 <= and_ln103_1_fu_321_p2;
        empty_reg_985 <= empty_fu_335_p2;
        icmp_ln108_reg_947 <= icmp_ln108_fu_303_p2;
        icmp_ln109_reg_964 <= icmp_ln109_fu_315_p2;
        select_ln103_4_reg_980 <= select_ln103_4_fu_327_p3;
        xor_ln103_reg_959 <= xor_ln103_fu_309_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln103_reg_943 <= icmp_ln103_fu_271_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        sum_7_reg_1086 <= grp_fu_839_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln103_fu_271_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln103_reg_943 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter14_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten238_load = 17'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten238_load = indvar_flatten238_fu_150;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        ap_sig_allocacmp_sum_5_load = grp_fu_839_p3;
    end else begin
        ap_sig_allocacmp_sum_5_load = sum_5_fu_154;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp1)) begin
        if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'd1 == and_ln110_reg_1025_pp0_iter6_reg))) begin
            ap_sig_allocacmp_sum_5_load_1 = select_ln108_2_fu_801_p3;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            ap_sig_allocacmp_sum_5_load_1 = grp_fu_839_p3;
        end else begin
            ap_sig_allocacmp_sum_5_load_1 = sum_5_fu_154;
        end
    end else begin
        ap_sig_allocacmp_sum_5_load_1 = sum_5_fu_154;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        ap_sig_allocacmp_x_load = add_ln110_1_fu_677_p2;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_106;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        fc_b_ce0_local = 1'b1;
    end else begin
        fc_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        fc_w_ce0_local = 1'b1;
    end else begin
        fc_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op190_write_state16 == 1'b1))) begin
        gmem_blk_n_W = m_axi_gmem_0_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_211_ce = 1'b1;
    end else begin
        grp_fu_211_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_830_ce = 1'b1;
    end else begin
        grp_fu_830_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_839_ce = 1'b1;
    end else begin
        grp_fu_839_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        layer2_out_ce0_local = 1'b1;
    end else begin
        layer2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op190_write_state16 == 1'b1))) begin
        m_axi_gmem_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_1_fu_277_p2 = (ap_sig_allocacmp_indvar_flatten238_load + 17'd1);

assign add_ln103_fu_297_p2 = (i_fu_146 + 4'd1);

assign add_ln108_1_fu_699_p2 = (select_ln108_fu_609_p3 + 14'd784);

assign add_ln108_2_fu_359_p2 = (indvar_flatten206_fu_142 + 15'd1);

assign add_ln108_fu_437_p2 = (select_ln103_1_fu_397_p3 + 5'd1);

assign add_ln109_1_fu_345_p2 = (indvar_flatten186_fu_130 + 10'd1);

assign add_ln109_fu_491_p2 = (y_5_mid2195_fu_443_p3 + 5'd1);

assign add_ln110_1_fu_677_p2 = (x_2_mid2_reg_1013 + 5'd1);

assign add_ln110_fu_688_p2 = (select_ln109_fu_623_p3 + 14'd28);

assign add_ln112_1_fu_767_p2 = (sub_ln110_fu_758_p2 + zext_ln112_3_fu_764_p1);

assign add_ln112_fu_657_p2 = (sub_ln112_fu_648_p2 + zext_ln112_1_fu_654_p1);

assign add_ln117_fu_671_p2 = (flat_idx_1_mid2_fu_616_p3 + 14'd1);

assign and_ln103_1_fu_321_p2 = (xor_ln103_fu_309_p2 & icmp_ln109_fu_315_p2);

assign and_ln103_fu_432_p2 = (xor_ln103_reg_959 & icmp_ln110_fu_426_p2);

assign and_ln110_fu_543_p2 = (icmp_ln110_1_fu_537_p2 & first_iter_8_mid2_fu_521_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_block_state16_io_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_block_state16_io_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_block_state16_io_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state16_io_grp1 = ((m_axi_gmem_0_WREADY == 1'b0) & (ap_predicate_op190_write_state16 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op190_write_state16 = ((icmp_ln108_1_reg_1052_pp0_iter14_reg == 1'd1) & (icmp_ln109_1_reg_1048_pp0_iter14_reg == 1'd1) & (icmp_ln110_2_reg_1044_pp0_iter14_reg == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign bitcast_ln122_fu_820_p1 = grp_fu_187_p_dout0;

assign empty_26_fu_497_p2 = (icmp_ln110_mid2205_fu_478_p2 | and_ln103_1_reg_969);

assign empty_27_fu_502_p2 = (icmp_ln108_reg_947 | empty_26_fu_497_p2);

assign empty_fu_335_p2 = (icmp_ln108_fu_303_p2 | and_ln103_1_fu_321_p2);

assign exitcond_flatten188_not_fu_468_p2 = (icmp_ln109_reg_964 ^ 1'd1);

assign fc_b_address0 = zext_ln103_fu_790_p1;

assign fc_w_address0 = zext_ln114_fu_778_p1;

assign first_iter_8306_fu_415_p2 = ((y_fu_126 == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_8_mid1_fu_515_p2 = ((add_ln109_fu_491_p2 == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_8_mid2203_fu_463_p2 = (or_ln103_1_fu_421_p2 | and_ln103_1_reg_969);

assign first_iter_8_mid2_fu_521_p3 = ((icmp_ln110_mid2205_fu_478_p2[0:0] == 1'b1) ? first_iter_8_mid1_fu_515_p2 : first_iter_8_mid2203_fu_463_p2);

assign first_iter_9303_fu_404_p2 = ((c_fu_134 == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_9_mid1_fu_450_p2 = ((add_ln108_fu_437_p2 == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_9_mid2_fu_456_p3 = ((and_ln103_1_reg_969[0:0] == 1'b1) ? first_iter_9_mid1_fu_450_p2 : or_ln103_fu_410_p2);

assign flat_idx_1_mid2199_fu_602_p3 = ((and_ln103_1_reg_969_pp0_iter2_reg[0:0] == 1'b1) ? add_ln108_119_fu_114 : select_ln103_3_fu_588_p3);

assign flat_idx_1_mid2_fu_616_p3 = ((icmp_ln110_mid2205_reg_1000[0:0] == 1'b1) ? add_ln11021_fu_122 : flat_idx_1_mid2199_fu_602_p3);

assign flat_idx_mid2194_fu_595_p3 = ((and_ln103_1_reg_969_pp0_iter2_reg[0:0] == 1'b1) ? add_ln108_119_fu_114 : select_ln103_2_fu_581_p3);

assign grp_fu_187_p_ce = grp_fu_211_ce;

assign grp_fu_187_p_din0 = sum_7_reg_1086;

assign grp_fu_830_p0 = 17'd12544;

assign grp_fu_830_p1 = grp_fu_830_p10;

assign grp_fu_830_p10 = select_ln103_4_fu_327_p3;

assign grp_fu_830_p2 = grp_fu_830_p20;

assign grp_fu_830_p20 = flat_idx_1_mid2_fu_616_p3;

assign icmp_ln103_fu_271_p2 = ((ap_sig_allocacmp_indvar_flatten238_load == 17'd125440) ? 1'b1 : 1'b0);

assign icmp_ln108_1_fu_705_p2 = ((select_ln108_1_reg_1006 == 5'd15) ? 1'b1 : 1'b0);

assign icmp_ln108_fu_303_p2 = ((indvar_flatten206_fu_142 == 15'd12544) ? 1'b1 : 1'b0);

assign icmp_ln109_1_fu_694_p2 = ((select_ln109_1_reg_1019 == 5'd27) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_315_p2 = ((indvar_flatten186_fu_130 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln110_1_fu_537_p2 = ((x_2_mid2_fu_507_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_2_fu_682_p2 = ((add_ln110_1_fu_677_p2 == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_426_p2 = ((ap_sig_allocacmp_x_load == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln110_mid2205_fu_478_p2 = (not_exitcond_flatten188_mid2237_fu_473_p2 & and_ln103_fu_432_p2);

assign layer2_out_address0 = zext_ln112_4_fu_773_p1;

assign layer2_out_ce0 = layer2_out_ce0_local;

assign m_axi_gmem_0_ARADDR = 64'd0;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 32'd0;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_ARVALID = 1'b0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_RREADY = 1'b0;

assign m_axi_gmem_0_WDATA = bitcast_ln122_reg_1091;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 4'd15;

assign m_axi_gmem_0_WUSER = 1'd0;

assign not_exitcond_flatten188_mid2237_fu_473_p2 = (icmp_ln108_reg_947 | exitcond_flatten188_not_fu_468_p2);

assign or_ln103_1_fu_421_p2 = (icmp_ln108_reg_947 | first_iter_8306_fu_415_p2);

assign or_ln103_fu_410_p2 = (icmp_ln108_reg_947 | first_iter_9303_fu_404_p2);

assign p_shl_fu_630_p3 = {{select_ln108_1_reg_1006}, {5'd0}};

assign select_ln103_1_fu_397_p3 = ((icmp_ln108_reg_947[0:0] == 1'b1) ? 5'd0 : c_fu_134);

assign select_ln103_2_fu_581_p3 = ((icmp_ln108_reg_947_pp0_iter2_reg[0:0] == 1'b1) ? 14'd0 : flat_idx_fu_118);

assign select_ln103_3_fu_588_p3 = ((icmp_ln108_reg_947_pp0_iter2_reg[0:0] == 1'b1) ? 14'd0 : flat_idx_1_fu_110);

assign select_ln103_4_fu_327_p3 = ((icmp_ln108_fu_303_p2[0:0] == 1'b1) ? add_ln103_fu_297_p2 : i_fu_146);

assign select_ln103_fu_574_p3 = ((icmp_ln108_reg_947_pp0_iter2_reg[0:0] == 1'b1) ? 14'd0 : indvars_iv136_fu_138);

assign select_ln108_1_fu_484_p3 = ((and_ln103_1_reg_969[0:0] == 1'b1) ? add_ln108_fu_437_p2 : select_ln103_1_fu_397_p3);

assign select_ln108_2_fu_801_p3 = ((first_iter_9_mid2_reg_995_pp0_iter6_reg[0:0] == 1'b1) ? sext_ln104_fu_797_p1 : ap_sig_allocacmp_sum_5_load);

assign select_ln108_3_fu_365_p3 = ((icmp_ln108_fu_303_p2[0:0] == 1'b1) ? 15'd1 : add_ln108_2_fu_359_p2);

assign select_ln108_fu_609_p3 = ((and_ln103_1_reg_969_pp0_iter2_reg[0:0] == 1'b1) ? add_ln108_119_fu_114 : select_ln103_fu_574_p3);

assign select_ln109_1_fu_529_p3 = ((icmp_ln110_mid2205_fu_478_p2[0:0] == 1'b1) ? add_ln109_fu_491_p2 : y_5_mid2195_fu_443_p3);

assign select_ln109_2_fu_351_p3 = ((empty_fu_335_p2[0:0] == 1'b1) ? 10'd1 : add_ln109_1_fu_345_p2);

assign select_ln109_fu_623_p3 = ((icmp_ln110_mid2205_reg_1000[0:0] == 1'b1) ? add_ln11021_fu_122 : flat_idx_mid2194_fu_595_p3);

assign sext_ln104_fu_797_p1 = $signed(fc_b_q0);

assign sub_ln110_fu_758_p2 = (tmp_63_fu_747_p3 - zext_ln112_2_fu_754_p1);

assign sub_ln112_fu_648_p2 = (p_shl_fu_630_p3 - zext_ln112_fu_644_p1);

assign tmp_62_fu_740_p3 = {{add_ln112_reg_1029}, {2'd0}};

assign tmp_63_fu_747_p3 = {{trunc_ln112_reg_1034}, {5'd0}};

assign tmp_fu_637_p3 = {{select_ln108_1_reg_1006}, {2'd0}};

assign trunc_ln112_fu_663_p1 = add_ln112_fu_657_p2[8:0];

assign x_2_mid2_fu_507_p3 = ((empty_27_fu_502_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_x_load);

assign xor_ln103_fu_309_p2 = (icmp_ln108_fu_303_p2 ^ 1'd1);

assign y_5_mid2195_fu_443_p3 = ((empty_reg_985[0:0] == 1'b1) ? 5'd0 : y_fu_126);

assign zext_ln103_fu_790_p1 = select_ln103_4_reg_980_pp0_iter5_reg;

assign zext_ln112_1_fu_654_p1 = select_ln109_1_reg_1019;

assign zext_ln112_2_fu_754_p1 = tmp_62_fu_740_p3;

assign zext_ln112_3_fu_764_p1 = x_2_mid2_reg_1013_pp0_iter3_reg;

assign zext_ln112_4_fu_773_p1 = add_ln112_1_fu_767_p2;

assign zext_ln112_fu_644_p1 = tmp_fu_637_p3;

assign zext_ln114_fu_778_p1 = grp_fu_830_p3;

endmodule //dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITIS_s
