// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dense_int8_dense_int8_Pipeline_VITIS_LOOP_71_6_VITIS_LOOP_72_7_VITIS_LOOP_73_8_VITIS_LOOP_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer2_out_address0,
        layer2_out_ce0,
        layer2_out_we0,
        layer2_out_d0,
        layer1_out_address0,
        layer1_out_ce0,
        layer1_out_q0,
        grp_fu_179_p_din0,
        grp_fu_179_p_din1,
        grp_fu_179_p_dout0,
        grp_fu_179_p_ce,
        grp_fu_187_p_din0,
        grp_fu_187_p_dout0,
        grp_fu_187_p_ce,
        grp_fu_183_p_din0,
        grp_fu_183_p_din1,
        grp_fu_183_p_opcode,
        grp_fu_183_p_dout0,
        grp_fu_183_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] layer2_out_address0;
output   layer2_out_ce0;
output   layer2_out_we0;
output  [7:0] layer2_out_d0;
output  [12:0] layer1_out_address0;
output   layer1_out_ce0;
input  [7:0] layer1_out_q0;
output  [31:0] grp_fu_179_p_din0;
output  [31:0] grp_fu_179_p_din1;
input  [31:0] grp_fu_179_p_dout0;
output   grp_fu_179_p_ce;
output  [31:0] grp_fu_187_p_din0;
input  [31:0] grp_fu_187_p_dout0;
output   grp_fu_187_p_ce;
output  [31:0] grp_fu_183_p_din0;
output  [31:0] grp_fu_183_p_din1;
output  [4:0] grp_fu_183_p_opcode;
input  [0:0] grp_fu_183_p_dout0;
output   grp_fu_183_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln71_fu_326_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [10:0] conv2_w_address0;
wire  signed [7:0] conv2_w_q0;
wire   [3:0] conv2_b_address0;
wire   [12:0] conv2_b_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln71_reg_1606;
reg   [0:0] icmp_ln71_reg_1606_pp0_iter1_reg;
wire   [0:0] icmp_ln72_fu_352_p2;
reg   [0:0] icmp_ln72_reg_1610;
reg   [0:0] icmp_ln72_reg_1610_pp0_iter2_reg;
reg   [0:0] icmp_ln72_reg_1610_pp0_iter3_reg;
reg   [0:0] icmp_ln72_reg_1610_pp0_iter4_reg;
reg   [0:0] icmp_ln72_reg_1610_pp0_iter5_reg;
reg   [0:0] icmp_ln72_reg_1610_pp0_iter6_reg;
reg   [0:0] icmp_ln72_reg_1610_pp0_iter7_reg;
wire   [0:0] xor_ln71_fu_358_p2;
reg   [0:0] xor_ln71_reg_1622;
reg   [0:0] xor_ln71_reg_1622_pp0_iter2_reg;
wire   [0:0] and_ln71_3_fu_376_p2;
reg   [0:0] and_ln71_3_reg_1628;
reg   [0:0] and_ln71_3_reg_1628_pp0_iter2_reg;
reg   [0:0] and_ln71_3_reg_1628_pp0_iter3_reg;
reg   [0:0] and_ln71_3_reg_1628_pp0_iter4_reg;
reg   [0:0] and_ln71_3_reg_1628_pp0_iter5_reg;
reg   [0:0] and_ln71_3_reg_1628_pp0_iter6_reg;
reg   [0:0] and_ln71_3_reg_1628_pp0_iter7_reg;
wire   [0:0] empty_fu_382_p2;
reg   [0:0] empty_reg_1638;
reg   [0:0] empty_reg_1638_pp0_iter2_reg;
reg   [0:0] empty_reg_1638_pp0_iter3_reg;
wire   [0:0] not_exitcond_flatten90_mid2178249_fu_394_p2;
reg   [0:0] not_exitcond_flatten90_mid2178249_reg_1644;
reg   [0:0] not_exitcond_flatten90_mid2178249_reg_1644_pp0_iter2_reg;
wire   [0:0] exitcond_flatten61_mid2127_fu_406_p2;
reg   [0:0] exitcond_flatten61_mid2127_reg_1650;
reg   [0:0] exitcond_flatten61_mid2127_reg_1650_pp0_iter2_reg;
reg   [0:0] exitcond_flatten61_mid2127_reg_1650_pp0_iter3_reg;
reg   [0:0] exitcond_flatten61_mid2127_reg_1650_pp0_iter4_reg;
reg   [0:0] exitcond_flatten61_mid2127_reg_1650_pp0_iter5_reg;
reg   [0:0] exitcond_flatten61_mid2127_reg_1650_pp0_iter6_reg;
reg   [0:0] exitcond_flatten61_mid2127_reg_1650_pp0_iter7_reg;
wire   [0:0] empty_19_fu_412_p2;
reg   [0:0] empty_19_reg_1662;
reg   [0:0] empty_19_reg_1662_pp0_iter2_reg;
wire   [7:0] add_ln77_1_fu_418_p2;
reg   [7:0] add_ln77_1_reg_1668;
wire   [0:0] exitcond_flatten44_mid2123_fu_476_p2;
reg   [0:0] exitcond_flatten44_mid2123_reg_1673;
wire   [0:0] empty_20_fu_481_p2;
reg   [0:0] empty_20_reg_1678;
wire   [0:0] not_exitcond_flatten61_mid2127_fu_485_p2;
reg   [0:0] not_exitcond_flatten61_mid2127_reg_1683;
wire   [0:0] exitcond_flatten44_mid287_fu_490_p2;
reg   [0:0] exitcond_flatten44_mid287_reg_1688;
reg   [0:0] exitcond_flatten44_mid287_reg_1688_pp0_iter3_reg;
reg   [0:0] exitcond_flatten44_mid287_reg_1688_pp0_iter4_reg;
reg   [0:0] exitcond_flatten44_mid287_reg_1688_pp0_iter5_reg;
reg   [0:0] exitcond_flatten44_mid287_reg_1688_pp0_iter6_reg;
reg   [0:0] exitcond_flatten44_mid287_reg_1688_pp0_iter7_reg;
wire   [0:0] empty_22_fu_501_p2;
reg   [0:0] empty_22_reg_1696;
wire   [0:0] first_iter_6281_fu_565_p2;
reg   [0:0] first_iter_6281_reg_1701;
reg   [0:0] first_iter_6281_reg_1701_pp0_iter4_reg;
reg   [0:0] first_iter_6281_reg_1701_pp0_iter5_reg;
reg   [0:0] first_iter_6281_reg_1701_pp0_iter6_reg;
reg   [0:0] first_iter_6281_reg_1701_pp0_iter7_reg;
wire   [0:0] first_iter_4286_fu_571_p2;
reg   [0:0] first_iter_4286_reg_1706;
reg   [0:0] first_iter_4286_reg_1706_pp0_iter4_reg;
reg   [0:0] first_iter_4286_reg_1706_pp0_iter5_reg;
reg   [0:0] first_iter_4286_reg_1706_pp0_iter6_reg;
reg   [0:0] first_iter_4286_reg_1706_pp0_iter7_reg;
wire   [0:0] first_iter_3288_fu_577_p2;
reg   [0:0] first_iter_3288_reg_1711;
reg   [0:0] first_iter_3288_reg_1711_pp0_iter4_reg;
reg   [0:0] first_iter_3288_reg_1711_pp0_iter5_reg;
reg   [0:0] first_iter_3288_reg_1711_pp0_iter6_reg;
reg   [0:0] first_iter_3288_reg_1711_pp0_iter7_reg;
wire   [4:0] select_ln71_1_fu_594_p3;
reg   [4:0] select_ln71_1_reg_1716;
reg   [4:0] select_ln71_1_reg_1716_pp0_iter4_reg;
reg   [4:0] select_ln71_1_reg_1716_pp0_iter5_reg;
reg   [4:0] select_ln71_1_reg_1716_pp0_iter6_reg;
wire   [4:0] add_ln72_fu_601_p2;
reg   [4:0] add_ln72_reg_1725;
reg   [4:0] add_ln72_reg_1725_pp0_iter4_reg;
reg   [4:0] add_ln72_reg_1725_pp0_iter5_reg;
reg   [4:0] add_ln72_reg_1725_pp0_iter6_reg;
reg   [4:0] add_ln72_reg_1725_pp0_iter7_reg;
wire   [4:0] select_ln72_fu_612_p3;
reg   [4:0] select_ln72_reg_1730;
reg   [4:0] select_ln72_reg_1730_pp0_iter4_reg;
reg   [4:0] select_ln72_reg_1730_pp0_iter5_reg;
reg   [4:0] select_ln72_reg_1730_pp0_iter6_reg;
reg   [4:0] select_ln72_reg_1730_pp0_iter7_reg;
wire   [3:0] add_ln77_fu_626_p2;
reg   [3:0] add_ln77_reg_1736;
reg   [3:0] add_ln77_reg_1736_pp0_iter4_reg;
reg   [3:0] add_ln77_reg_1736_pp0_iter5_reg;
reg   [3:0] add_ln77_reg_1736_pp0_iter6_reg;
wire   [0:0] icmp_ln79_mid258_fu_654_p2;
reg   [0:0] icmp_ln79_mid258_reg_1741;
reg   [0:0] icmp_ln79_mid258_reg_1741_pp0_iter4_reg;
reg   [0:0] icmp_ln79_mid258_reg_1741_pp0_iter5_reg;
reg   [0:0] icmp_ln79_mid258_reg_1741_pp0_iter6_reg;
reg   [0:0] icmp_ln79_mid258_reg_1741_pp0_iter7_reg;
wire   [3:0] select_ln77_fu_660_p3;
reg   [3:0] select_ln77_reg_1746;
wire   [1:0] add_ln78_fu_667_p2;
reg   [1:0] add_ln78_reg_1754;
reg   [1:0] add_ln78_reg_1754_pp0_iter4_reg;
reg   [1:0] add_ln78_reg_1754_pp0_iter5_reg;
reg   [1:0] add_ln78_reg_1754_pp0_iter6_reg;
wire   [1:0] kx_mid2_fu_688_p3;
reg   [1:0] kx_mid2_reg_1759;
reg   [1:0] kx_mid2_reg_1759_pp0_iter4_reg;
reg   [1:0] kx_mid2_reg_1759_pp0_iter5_reg;
reg   [1:0] kx_mid2_reg_1759_pp0_iter6_reg;
wire   [1:0] select_ln78_fu_696_p3;
reg   [1:0] select_ln78_reg_1766;
wire   [0:0] icmp_ln79_2_fu_710_p2;
reg   [0:0] icmp_ln79_2_reg_1773;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter4_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter5_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter6_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter7_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter8_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter9_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter10_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter11_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter12_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter13_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter14_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter15_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter16_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter17_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter18_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter19_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter20_reg;
reg   [0:0] icmp_ln79_2_reg_1773_pp0_iter21_reg;
wire   [0:0] icmp_ln78_1_fu_716_p2;
reg   [0:0] icmp_ln78_1_reg_1777;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter4_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter5_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter6_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter7_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter8_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter9_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter10_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter11_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter12_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter13_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter14_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter15_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter16_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter17_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter18_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter19_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter20_reg;
reg   [0:0] icmp_ln78_1_reg_1777_pp0_iter21_reg;
wire   [0:0] icmp_ln77_1_fu_722_p2;
reg   [0:0] icmp_ln77_1_reg_1781;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter4_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter5_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter6_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter7_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter8_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter9_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter10_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter11_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter12_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter13_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter14_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter15_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter16_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter17_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter18_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter19_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter20_reg;
reg   [0:0] icmp_ln77_1_reg_1781_pp0_iter21_reg;
wire   [0:0] first_iter_5284_fu_756_p2;
reg   [0:0] first_iter_5284_reg_1785;
reg   [0:0] first_iter_5284_reg_1785_pp0_iter5_reg;
reg   [0:0] first_iter_5284_reg_1785_pp0_iter6_reg;
reg   [0:0] first_iter_5284_reg_1785_pp0_iter7_reg;
wire   [4:0] add_ln73_fu_769_p2;
reg   [4:0] add_ln73_reg_1790;
reg   [4:0] add_ln73_reg_1790_pp0_iter5_reg;
reg   [4:0] add_ln73_reg_1790_pp0_iter6_reg;
reg   [4:0] add_ln73_reg_1790_pp0_iter7_reg;
wire   [4:0] select_ln73_fu_775_p3;
reg   [4:0] select_ln73_reg_1795;
reg   [4:0] select_ln73_reg_1795_pp0_iter5_reg;
reg   [4:0] select_ln73_reg_1795_pp0_iter6_reg;
reg   [4:0] select_ln73_reg_1795_pp0_iter7_reg;
wire   [9:0] add_ln85_fu_887_p2;
reg   [9:0] add_ln85_reg_1800;
wire   [7:0] trunc_ln85_fu_893_p1;
reg   [7:0] trunc_ln85_reg_1805;
wire   [0:0] icmp_ln84_fu_910_p2;
reg   [0:0] icmp_ln84_reg_1810;
wire  signed [5:0] add_ln81_1_fu_928_p2;
reg  signed [5:0] add_ln81_1_reg_1815;
wire   [10:0] add_ln89_2_fu_950_p2;
reg   [10:0] add_ln89_2_reg_1821;
wire   [0:0] and_ln84_fu_1004_p2;
reg   [0:0] and_ln84_reg_1831;
wire   [0:0] first_iter_4_mid1_fu_1028_p2;
reg   [0:0] first_iter_4_mid1_reg_1851;
wire   [0:0] first_iter_3_mid1_fu_1033_p2;
reg   [0:0] first_iter_3_mid1_reg_1856;
wire   [9:0] sub_ln94_fu_1060_p2;
reg   [9:0] sub_ln94_reg_1861;
wire   [0:0] icmp_ln79_1_fu_1066_p2;
reg   [0:0] icmp_ln79_1_reg_1871;
wire   [13:0] add_ln94_1_fu_1287_p2;
reg   [13:0] add_ln94_1_reg_1884;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter9_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter10_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter11_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter12_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter13_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter14_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter15_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter16_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter17_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter18_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter19_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter20_reg;
reg   [13:0] add_ln94_1_reg_1884_pp0_iter21_reg;
wire  signed [31:0] grp_fu_1505_p3;
reg  signed [31:0] sum_3_reg_1889;
reg   [31:0] conv_i1_reg_1894;
reg   [31:0] val_reg_1899;
wire   [31:0] data_fu_1297_p1;
reg   [31:0] data_reg_1906;
reg   [31:0] data_reg_1906_pp0_iter21_reg;
wire   [22:0] trunc_ln17_fu_1310_p1;
reg   [22:0] trunc_ln17_reg_1911;
wire   [0:0] icmp_ln17_fu_1314_p2;
reg   [0:0] icmp_ln17_reg_1917;
wire   [0:0] tmp_10_fu_1338_p3;
reg   [0:0] tmp_10_reg_1922;
wire   [8:0] select_ln18_fu_1356_p3;
reg   [8:0] select_ln18_reg_1927;
wire   [0:0] or_ln17_fu_1369_p2;
reg   [0:0] or_ln17_reg_1932;
reg   [0:0] tmp_7_reg_1938;
wire   [0:0] grp_fu_263_p2;
reg   [0:0] tmp_8_reg_1943;
wire   [7:0] val_1_fu_1426_p3;
reg   [7:0] val_1_reg_1948;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln85_1_fu_994_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln90_fu_1009_p1;
wire   [63:0] zext_ln71_fu_1038_p1;
wire   [63:0] zext_ln94_4_fu_1433_p1;
reg   [31:0] sum_fu_146;
wire   [31:0] select_ln72_2_fu_1220_p3;
wire   [31:0] sum_11_mid275_fu_1127_p3;
reg   [31:0] ap_sig_allocacmp_sum_load;
reg  signed [31:0] ap_sig_allocacmp_sum_load_1;
wire   [0:0] or_ln79_2_fu_1202_p2;
reg   [1:0] kx_fu_150;
wire   [1:0] add_ln79_fu_704_p2;
wire    ap_loop_init;
reg   [1:0] ky_fu_154;
reg   [3:0] indvar_flatten42_fu_158;
wire   [3:0] select_ln78_1_fu_512_p3;
reg   [3:0] ic_fu_162;
reg   [7:0] indvar_flatten59_fu_166;
wire   [7:0] select_ln77_1_fu_520_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten59_load;
reg   [4:0] x_fu_170;
reg   [11:0] indvar_flatten88_fu_174;
wire   [11:0] select_ln73_1_fu_430_p3;
reg   [4:0] y_fu_178;
reg   [15:0] indvar_flatten128_fu_182;
wire   [15:0] select_ln72_3_fu_444_p3;
reg   [4:0] oc_fu_186;
reg   [19:0] indvar_flatten179_fu_190;
wire   [19:0] add_ln71_1_fu_332_p2;
reg   [19:0] ap_sig_allocacmp_indvar_flatten179_load;
reg   [31:0] sext_ln8910_fu_194;
wire   [31:0] select_ln72_1_fu_1212_p3;
reg    layer1_out_ce0_local;
reg    conv2_w_ce0_local;
reg    conv2_b_ce0_local;
reg    layer2_out_we0_local;
wire   [7:0] retval_0_i1_fu_1484_p9;
reg    layer2_out_ce0_local;
wire   [0:0] icmp_ln73_fu_370_p2;
wire   [0:0] exitcond_flatten90_not250_fu_388_p2;
wire   [0:0] icmp_ln77_fu_364_p2;
wire   [0:0] and_ln71_2_fu_400_p2;
wire   [11:0] add_ln73_1_fu_424_p2;
wire   [15:0] add_ln72_1_fu_438_p2;
wire   [0:0] icmp_ln78_fu_465_p2;
wire   [0:0] and_ln71_1_fu_471_p2;
wire   [0:0] empty_21_fu_496_p2;
wire   [3:0] add_ln78_1_fu_506_p2;
wire   [0:0] icmp_ln79_fu_583_p2;
wire   [4:0] add_ln71_fu_552_p2;
wire   [4:0] select_ln71_fu_558_p3;
wire   [0:0] and_ln71_fu_589_p2;
wire   [3:0] ic_mid267_fu_619_p3;
wire   [0:0] exitcond_flatten44_mid2123_not_fu_639_p2;
wire   [0:0] icmp_ln79_mid2119_fu_607_p2;
wire   [0:0] icmp_ln79_mid283_fu_649_p2;
wire   [0:0] not_exitcond_flatten44_mid287_fu_644_p2;
wire   [1:0] ky_mid250_fu_632_p3;
wire   [0:0] empty_23_fu_673_p2;
wire   [0:0] empty_24_fu_677_p2;
wire   [0:0] empty_25_fu_683_p2;
wire   [4:0] x_1_mid296_fu_762_p3;
wire   [7:0] tmp_1_fu_789_p3;
wire   [10:0] p_shl1_fu_782_p3;
wire   [10:0] zext_ln72_fu_796_p1;
wire   [5:0] tmp_4_fu_820_p3;
wire   [8:0] p_shl2_fu_813_p3;
wire   [8:0] zext_ln85_fu_827_p1;
wire   [8:0] sub_ln85_fu_831_p2;
wire   [6:0] tmp_5_fu_844_p3;
wire   [7:0] zext_ln89_1_fu_851_p1;
wire   [7:0] zext_ln77_1_fu_841_p1;
wire   [7:0] add_ln89_3_fu_855_p2;
wire   [1:0] add_ln80_fu_868_p2;
wire  signed [5:0] sext_ln80_fu_873_p1;
wire   [5:0] zext_ln72_1_fu_806_p1;
wire  signed [5:0] add_ln80_1_fu_877_p2;
wire   [9:0] zext_ln77_fu_837_p1;
wire  signed [9:0] sext_ln85_fu_883_p1;
wire   [3:0] p_shl4_fu_897_p3;
wire   [3:0] zext_ln78_1_fu_865_p1;
wire   [1:0] add_ln81_fu_919_p2;
wire  signed [5:0] sext_ln81_fu_924_p1;
wire   [5:0] zext_ln73_fu_809_p1;
wire   [10:0] zext_ln78_fu_861_p1;
wire   [10:0] add_ln72_2_fu_800_p2;
wire   [3:0] sub_ln89_1_fu_904_p2;
wire   [3:0] zext_ln79_fu_916_p1;
wire   [3:0] add_ln89_1_fu_940_p2;
wire   [10:0] zext_ln89_fu_946_p1;
wire   [10:0] add_ln89_fu_934_p2;
wire   [11:0] tmp_6_fu_968_p3;
wire   [12:0] p_shl3_fu_961_p3;
wire  signed [12:0] sext_ln89_1_fu_975_p1;
wire   [12:0] sub_ln89_fu_979_p2;
wire  signed [12:0] sext_ln85_1_fu_985_p1;
wire   [12:0] add_ln85_1_fu_988_p2;
wire   [0:0] icmp_ln84_1_fu_999_p2;
wire  signed [7:0] val_in_1_fu_1013_p3;
wire   [6:0] tmp_fu_1049_p3;
wire   [9:0] p_shl_fu_1042_p3;
wire   [9:0] zext_ln94_fu_1056_p1;
wire   [0:0] first_iter_6_mid1_fu_1100_p2;
wire   [0:0] or_ln71_fu_1077_p2;
wire   [0:0] or_ln71_1_fu_1081_p2;
wire   [0:0] or_ln71_2_fu_1085_p2;
wire   [0:0] or_ln71_3_fu_1089_p2;
wire   [31:0] sum_11_mid2107_fu_1093_p3;
wire   [0:0] first_iter_5_mid1_fu_1134_p2;
wire   [0:0] first_iter_5_mid2109_fu_1112_p2;
wire   [0:0] first_iter_4_mid2113_fu_1117_p2;
wire   [0:0] first_iter_3_mid2117_fu_1122_p2;
wire   [0:0] first_iter_4_mid277_fu_1146_p2;
wire   [0:0] first_iter_3_mid281_fu_1151_p2;
wire   [0:0] first_iter_3_mid256_fu_1162_p2;
wire   [0:0] first_iter_3_mid2_fu_1167_p3;
wire   [0:0] xor_ln79_fu_1173_p2;
wire   [0:0] first_iter_4_mid2_fu_1156_p3;
wire   [0:0] or_ln79_fu_1179_p2;
wire   [0:0] xor_ln79_1_fu_1184_p2;
wire   [0:0] first_iter_5_mid2_fu_1139_p3;
wire   [0:0] or_ln79_1_fu_1190_p2;
wire   [0:0] xor_ln79_2_fu_1196_p2;
wire   [0:0] first_iter_6_mid2_fu_1105_p3;
wire  signed [31:0] sext_ln89_fu_1208_p1;
wire   [9:0] zext_ln94_1_fu_1246_p1;
wire   [9:0] add_ln94_fu_1249_p2;
wire   [8:0] trunc_ln94_fu_1254_p1;
wire   [11:0] tmp_2_fu_1258_p3;
wire   [13:0] tmp_3_fu_1266_p3;
wire   [13:0] zext_ln94_2_fu_1274_p1;
wire   [13:0] sub_ln72_fu_1278_p2;
wire   [13:0] zext_ln94_3_fu_1284_p1;
wire   [7:0] tmp_s_fu_1300_p4;
wire   [7:0] xs_exp_fu_1320_p3;
wire   [8:0] zext_ln317_fu_1328_p1;
wire   [8:0] add_ln317_fu_1332_p2;
wire   [7:0] sub_ln18_fu_1346_p2;
wire  signed [8:0] sext_ln18_fu_1352_p1;
wire   [0:0] icmp_ln17_1_fu_1364_p2;
wire   [24:0] mantissa_fu_1374_p4;
wire  signed [31:0] sext_ln18_1_fu_1387_p1;
wire   [54:0] zext_ln15_fu_1383_p1;
wire   [54:0] zext_ln18_fu_1390_p1;
wire   [54:0] lshr_ln18_fu_1394_p2;
wire   [54:0] shl_ln18_fu_1400_p2;
wire   [7:0] tmp_9_fu_1406_p4;
wire   [7:0] tmp_11_fu_1416_p4;
wire   [0:0] xs_sign_fu_1445_p3;
wire   [7:0] sub_ln59_fu_1452_p2;
wire   [0:0] and_ln17_fu_1437_p2;
wire   [0:0] and_ln18_fu_1441_p2;
wire   [0:0] xor_ln17_fu_1464_p2;
wire   [0:0] and_ln18_1_fu_1470_p2;
wire   [7:0] retval_0_i1_fu_1484_p6;
wire   [7:0] retval_0_i1_fu_1484_p7;
wire   [1:0] retval_0_i1_fu_1484_p8;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [1:0] retval_0_i1_fu_1484_p1;
wire   [1:0] retval_0_i1_fu_1484_p3;
wire   [1:0] retval_0_i1_fu_1484_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 sum_fu_146 = 32'd0;
#0 kx_fu_150 = 2'd0;
#0 ky_fu_154 = 2'd0;
#0 indvar_flatten42_fu_158 = 4'd0;
#0 ic_fu_162 = 4'd0;
#0 indvar_flatten59_fu_166 = 8'd0;
#0 x_fu_170 = 5'd0;
#0 indvar_flatten88_fu_174 = 12'd0;
#0 y_fu_178 = 5'd0;
#0 indvar_flatten128_fu_182 = 16'd0;
#0 oc_fu_186 = 5'd0;
#0 indvar_flatten179_fu_190 = 20'd0;
#0 sext_ln8910_fu_194 = 32'd0;
#0 ap_done_reg = 1'b0;
end

dense_int8_dense_int8_Pipeline_VITIS_LOOP_71_6_VITIS_LOOP_72_7_VITIS_LOOP_73_8_VITIS_LOOdEe #(
    .DataWidth( 8 ),
    .AddressRange( 1152 ),
    .AddressWidth( 11 ))
conv2_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv2_w_address0),
    .ce0(conv2_w_ce0_local),
    .q0(conv2_w_q0)
);

dense_int8_dense_int8_Pipeline_VITIS_LOOP_71_6_VITIS_LOOP_72_7_VITIS_LOOP_73_8_VITIS_LOOeOg #(
    .DataWidth( 13 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
conv2_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv2_b_address0),
    .ce0(conv2_b_ce0_local),
    .q0(conv2_b_q0)
);

dense_int8_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(val_reg_1899),
    .din1(32'd1123942400),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_263_p2)
);

(* dissolve_hierarchy = "yes" *) dense_int8_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U29(
    .din0(8'd0),
    .din1(8'd127),
    .din2(retval_0_i1_fu_1484_p6),
    .def(retval_0_i1_fu_1484_p7),
    .sel(retval_0_i1_fu_1484_p8),
    .dout(retval_0_i1_fu_1484_p9)
);

dense_int8_mac_muladd_8s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_4_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv2_w_q0),
    .din1(val_in_1_fu_1013_p3),
    .din2(ap_sig_allocacmp_sum_load_1),
    .ce(1'b1),
    .dout(grp_fu_1505_p3)
);

dense_int8_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter21_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ic_fu_162 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            ic_fu_162 <= select_ln77_fu_660_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten128_fu_182 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln71_reg_1606 == 1'd0))) begin
            indvar_flatten128_fu_182 <= select_ln72_3_fu_444_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln71_fu_326_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten179_fu_190 <= add_ln71_1_fu_332_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten179_fu_190 <= 20'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten42_fu_158 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln71_reg_1606_pp0_iter1_reg == 1'd0))) begin
            indvar_flatten42_fu_158 <= select_ln78_1_fu_512_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten59_fu_166 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln71_reg_1606_pp0_iter1_reg == 1'd0))) begin
            indvar_flatten59_fu_166 <= select_ln77_1_fu_520_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten88_fu_174 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln71_reg_1606 == 1'd0))) begin
            indvar_flatten88_fu_174 <= select_ln73_1_fu_430_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            kx_fu_150 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            kx_fu_150 <= add_ln79_fu_704_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ky_fu_154 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            ky_fu_154 <= select_ln78_fu_696_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oc_fu_186 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            oc_fu_186 <= select_ln71_1_fu_594_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((or_ln79_2_fu_1202_p2 == 1'd1) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
            sum_fu_146 <= sum_11_mid275_fu_1127_p3;
        end else if (((or_ln79_2_fu_1202_p2 == 1'd0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
            sum_fu_146 <= select_ln72_2_fu_1220_p3;
        end else if ((ap_enable_reg_pp0_iter9 == 1'b1)) begin
            sum_fu_146 <= grp_fu_1505_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_fu_170 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            x_fu_170 <= select_ln73_fu_775_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_fu_178 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            y_fu_178 <= select_ln72_fu_612_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln72_reg_1725 <= add_ln72_fu_601_p2;
        add_ln72_reg_1725_pp0_iter4_reg <= add_ln72_reg_1725;
        add_ln72_reg_1725_pp0_iter5_reg <= add_ln72_reg_1725_pp0_iter4_reg;
        add_ln72_reg_1725_pp0_iter6_reg <= add_ln72_reg_1725_pp0_iter5_reg;
        add_ln72_reg_1725_pp0_iter7_reg <= add_ln72_reg_1725_pp0_iter6_reg;
        add_ln73_reg_1790 <= add_ln73_fu_769_p2;
        add_ln73_reg_1790_pp0_iter5_reg <= add_ln73_reg_1790;
        add_ln73_reg_1790_pp0_iter6_reg <= add_ln73_reg_1790_pp0_iter5_reg;
        add_ln73_reg_1790_pp0_iter7_reg <= add_ln73_reg_1790_pp0_iter6_reg;
        add_ln77_reg_1736 <= add_ln77_fu_626_p2;
        add_ln77_reg_1736_pp0_iter4_reg <= add_ln77_reg_1736;
        add_ln77_reg_1736_pp0_iter5_reg <= add_ln77_reg_1736_pp0_iter4_reg;
        add_ln77_reg_1736_pp0_iter6_reg <= add_ln77_reg_1736_pp0_iter5_reg;
        add_ln78_reg_1754 <= add_ln78_fu_667_p2;
        add_ln78_reg_1754_pp0_iter4_reg <= add_ln78_reg_1754;
        add_ln78_reg_1754_pp0_iter5_reg <= add_ln78_reg_1754_pp0_iter4_reg;
        add_ln78_reg_1754_pp0_iter6_reg <= add_ln78_reg_1754_pp0_iter5_reg;
        add_ln81_1_reg_1815 <= add_ln81_1_fu_928_p2;
        add_ln85_reg_1800 <= add_ln85_fu_887_p2;
        add_ln89_2_reg_1821 <= add_ln89_2_fu_950_p2;
        add_ln94_1_reg_1884 <= add_ln94_1_fu_1287_p2;
        add_ln94_1_reg_1884_pp0_iter10_reg <= add_ln94_1_reg_1884_pp0_iter9_reg;
        add_ln94_1_reg_1884_pp0_iter11_reg <= add_ln94_1_reg_1884_pp0_iter10_reg;
        add_ln94_1_reg_1884_pp0_iter12_reg <= add_ln94_1_reg_1884_pp0_iter11_reg;
        add_ln94_1_reg_1884_pp0_iter13_reg <= add_ln94_1_reg_1884_pp0_iter12_reg;
        add_ln94_1_reg_1884_pp0_iter14_reg <= add_ln94_1_reg_1884_pp0_iter13_reg;
        add_ln94_1_reg_1884_pp0_iter15_reg <= add_ln94_1_reg_1884_pp0_iter14_reg;
        add_ln94_1_reg_1884_pp0_iter16_reg <= add_ln94_1_reg_1884_pp0_iter15_reg;
        add_ln94_1_reg_1884_pp0_iter17_reg <= add_ln94_1_reg_1884_pp0_iter16_reg;
        add_ln94_1_reg_1884_pp0_iter18_reg <= add_ln94_1_reg_1884_pp0_iter17_reg;
        add_ln94_1_reg_1884_pp0_iter19_reg <= add_ln94_1_reg_1884_pp0_iter18_reg;
        add_ln94_1_reg_1884_pp0_iter20_reg <= add_ln94_1_reg_1884_pp0_iter19_reg;
        add_ln94_1_reg_1884_pp0_iter21_reg <= add_ln94_1_reg_1884_pp0_iter20_reg;
        add_ln94_1_reg_1884_pp0_iter9_reg <= add_ln94_1_reg_1884;
        and_ln71_3_reg_1628_pp0_iter2_reg <= and_ln71_3_reg_1628;
        and_ln71_3_reg_1628_pp0_iter3_reg <= and_ln71_3_reg_1628_pp0_iter2_reg;
        and_ln71_3_reg_1628_pp0_iter4_reg <= and_ln71_3_reg_1628_pp0_iter3_reg;
        and_ln71_3_reg_1628_pp0_iter5_reg <= and_ln71_3_reg_1628_pp0_iter4_reg;
        and_ln71_3_reg_1628_pp0_iter6_reg <= and_ln71_3_reg_1628_pp0_iter5_reg;
        and_ln71_3_reg_1628_pp0_iter7_reg <= and_ln71_3_reg_1628_pp0_iter6_reg;
        and_ln84_reg_1831 <= and_ln84_fu_1004_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        conv_i1_reg_1894 <= grp_fu_187_p_dout0;
        data_reg_1906 <= data_fu_1297_p1;
        data_reg_1906_pp0_iter21_reg <= data_reg_1906;
        empty_19_reg_1662_pp0_iter2_reg <= empty_19_reg_1662;
        empty_20_reg_1678 <= empty_20_fu_481_p2;
        empty_22_reg_1696 <= empty_22_fu_501_p2;
        empty_reg_1638_pp0_iter2_reg <= empty_reg_1638;
        empty_reg_1638_pp0_iter3_reg <= empty_reg_1638_pp0_iter2_reg;
        exitcond_flatten44_mid2123_reg_1673 <= exitcond_flatten44_mid2123_fu_476_p2;
        exitcond_flatten44_mid287_reg_1688 <= exitcond_flatten44_mid287_fu_490_p2;
        exitcond_flatten44_mid287_reg_1688_pp0_iter3_reg <= exitcond_flatten44_mid287_reg_1688;
        exitcond_flatten44_mid287_reg_1688_pp0_iter4_reg <= exitcond_flatten44_mid287_reg_1688_pp0_iter3_reg;
        exitcond_flatten44_mid287_reg_1688_pp0_iter5_reg <= exitcond_flatten44_mid287_reg_1688_pp0_iter4_reg;
        exitcond_flatten44_mid287_reg_1688_pp0_iter6_reg <= exitcond_flatten44_mid287_reg_1688_pp0_iter5_reg;
        exitcond_flatten44_mid287_reg_1688_pp0_iter7_reg <= exitcond_flatten44_mid287_reg_1688_pp0_iter6_reg;
        exitcond_flatten61_mid2127_reg_1650_pp0_iter2_reg <= exitcond_flatten61_mid2127_reg_1650;
        exitcond_flatten61_mid2127_reg_1650_pp0_iter3_reg <= exitcond_flatten61_mid2127_reg_1650_pp0_iter2_reg;
        exitcond_flatten61_mid2127_reg_1650_pp0_iter4_reg <= exitcond_flatten61_mid2127_reg_1650_pp0_iter3_reg;
        exitcond_flatten61_mid2127_reg_1650_pp0_iter5_reg <= exitcond_flatten61_mid2127_reg_1650_pp0_iter4_reg;
        exitcond_flatten61_mid2127_reg_1650_pp0_iter6_reg <= exitcond_flatten61_mid2127_reg_1650_pp0_iter5_reg;
        exitcond_flatten61_mid2127_reg_1650_pp0_iter7_reg <= exitcond_flatten61_mid2127_reg_1650_pp0_iter6_reg;
        first_iter_3288_reg_1711 <= first_iter_3288_fu_577_p2;
        first_iter_3288_reg_1711_pp0_iter4_reg <= first_iter_3288_reg_1711;
        first_iter_3288_reg_1711_pp0_iter5_reg <= first_iter_3288_reg_1711_pp0_iter4_reg;
        first_iter_3288_reg_1711_pp0_iter6_reg <= first_iter_3288_reg_1711_pp0_iter5_reg;
        first_iter_3288_reg_1711_pp0_iter7_reg <= first_iter_3288_reg_1711_pp0_iter6_reg;
        first_iter_3_mid1_reg_1856 <= first_iter_3_mid1_fu_1033_p2;
        first_iter_4286_reg_1706 <= first_iter_4286_fu_571_p2;
        first_iter_4286_reg_1706_pp0_iter4_reg <= first_iter_4286_reg_1706;
        first_iter_4286_reg_1706_pp0_iter5_reg <= first_iter_4286_reg_1706_pp0_iter4_reg;
        first_iter_4286_reg_1706_pp0_iter6_reg <= first_iter_4286_reg_1706_pp0_iter5_reg;
        first_iter_4286_reg_1706_pp0_iter7_reg <= first_iter_4286_reg_1706_pp0_iter6_reg;
        first_iter_4_mid1_reg_1851 <= first_iter_4_mid1_fu_1028_p2;
        first_iter_5284_reg_1785 <= first_iter_5284_fu_756_p2;
        first_iter_5284_reg_1785_pp0_iter5_reg <= first_iter_5284_reg_1785;
        first_iter_5284_reg_1785_pp0_iter6_reg <= first_iter_5284_reg_1785_pp0_iter5_reg;
        first_iter_5284_reg_1785_pp0_iter7_reg <= first_iter_5284_reg_1785_pp0_iter6_reg;
        first_iter_6281_reg_1701 <= first_iter_6281_fu_565_p2;
        first_iter_6281_reg_1701_pp0_iter4_reg <= first_iter_6281_reg_1701;
        first_iter_6281_reg_1701_pp0_iter5_reg <= first_iter_6281_reg_1701_pp0_iter4_reg;
        first_iter_6281_reg_1701_pp0_iter6_reg <= first_iter_6281_reg_1701_pp0_iter5_reg;
        first_iter_6281_reg_1701_pp0_iter7_reg <= first_iter_6281_reg_1701_pp0_iter6_reg;
        icmp_ln17_reg_1917 <= icmp_ln17_fu_1314_p2;
        icmp_ln72_reg_1610_pp0_iter2_reg <= icmp_ln72_reg_1610;
        icmp_ln72_reg_1610_pp0_iter3_reg <= icmp_ln72_reg_1610_pp0_iter2_reg;
        icmp_ln72_reg_1610_pp0_iter4_reg <= icmp_ln72_reg_1610_pp0_iter3_reg;
        icmp_ln72_reg_1610_pp0_iter5_reg <= icmp_ln72_reg_1610_pp0_iter4_reg;
        icmp_ln72_reg_1610_pp0_iter6_reg <= icmp_ln72_reg_1610_pp0_iter5_reg;
        icmp_ln72_reg_1610_pp0_iter7_reg <= icmp_ln72_reg_1610_pp0_iter6_reg;
        icmp_ln77_1_reg_1781 <= icmp_ln77_1_fu_722_p2;
        icmp_ln77_1_reg_1781_pp0_iter10_reg <= icmp_ln77_1_reg_1781_pp0_iter9_reg;
        icmp_ln77_1_reg_1781_pp0_iter11_reg <= icmp_ln77_1_reg_1781_pp0_iter10_reg;
        icmp_ln77_1_reg_1781_pp0_iter12_reg <= icmp_ln77_1_reg_1781_pp0_iter11_reg;
        icmp_ln77_1_reg_1781_pp0_iter13_reg <= icmp_ln77_1_reg_1781_pp0_iter12_reg;
        icmp_ln77_1_reg_1781_pp0_iter14_reg <= icmp_ln77_1_reg_1781_pp0_iter13_reg;
        icmp_ln77_1_reg_1781_pp0_iter15_reg <= icmp_ln77_1_reg_1781_pp0_iter14_reg;
        icmp_ln77_1_reg_1781_pp0_iter16_reg <= icmp_ln77_1_reg_1781_pp0_iter15_reg;
        icmp_ln77_1_reg_1781_pp0_iter17_reg <= icmp_ln77_1_reg_1781_pp0_iter16_reg;
        icmp_ln77_1_reg_1781_pp0_iter18_reg <= icmp_ln77_1_reg_1781_pp0_iter17_reg;
        icmp_ln77_1_reg_1781_pp0_iter19_reg <= icmp_ln77_1_reg_1781_pp0_iter18_reg;
        icmp_ln77_1_reg_1781_pp0_iter20_reg <= icmp_ln77_1_reg_1781_pp0_iter19_reg;
        icmp_ln77_1_reg_1781_pp0_iter21_reg <= icmp_ln77_1_reg_1781_pp0_iter20_reg;
        icmp_ln77_1_reg_1781_pp0_iter4_reg <= icmp_ln77_1_reg_1781;
        icmp_ln77_1_reg_1781_pp0_iter5_reg <= icmp_ln77_1_reg_1781_pp0_iter4_reg;
        icmp_ln77_1_reg_1781_pp0_iter6_reg <= icmp_ln77_1_reg_1781_pp0_iter5_reg;
        icmp_ln77_1_reg_1781_pp0_iter7_reg <= icmp_ln77_1_reg_1781_pp0_iter6_reg;
        icmp_ln77_1_reg_1781_pp0_iter8_reg <= icmp_ln77_1_reg_1781_pp0_iter7_reg;
        icmp_ln77_1_reg_1781_pp0_iter9_reg <= icmp_ln77_1_reg_1781_pp0_iter8_reg;
        icmp_ln78_1_reg_1777 <= icmp_ln78_1_fu_716_p2;
        icmp_ln78_1_reg_1777_pp0_iter10_reg <= icmp_ln78_1_reg_1777_pp0_iter9_reg;
        icmp_ln78_1_reg_1777_pp0_iter11_reg <= icmp_ln78_1_reg_1777_pp0_iter10_reg;
        icmp_ln78_1_reg_1777_pp0_iter12_reg <= icmp_ln78_1_reg_1777_pp0_iter11_reg;
        icmp_ln78_1_reg_1777_pp0_iter13_reg <= icmp_ln78_1_reg_1777_pp0_iter12_reg;
        icmp_ln78_1_reg_1777_pp0_iter14_reg <= icmp_ln78_1_reg_1777_pp0_iter13_reg;
        icmp_ln78_1_reg_1777_pp0_iter15_reg <= icmp_ln78_1_reg_1777_pp0_iter14_reg;
        icmp_ln78_1_reg_1777_pp0_iter16_reg <= icmp_ln78_1_reg_1777_pp0_iter15_reg;
        icmp_ln78_1_reg_1777_pp0_iter17_reg <= icmp_ln78_1_reg_1777_pp0_iter16_reg;
        icmp_ln78_1_reg_1777_pp0_iter18_reg <= icmp_ln78_1_reg_1777_pp0_iter17_reg;
        icmp_ln78_1_reg_1777_pp0_iter19_reg <= icmp_ln78_1_reg_1777_pp0_iter18_reg;
        icmp_ln78_1_reg_1777_pp0_iter20_reg <= icmp_ln78_1_reg_1777_pp0_iter19_reg;
        icmp_ln78_1_reg_1777_pp0_iter21_reg <= icmp_ln78_1_reg_1777_pp0_iter20_reg;
        icmp_ln78_1_reg_1777_pp0_iter4_reg <= icmp_ln78_1_reg_1777;
        icmp_ln78_1_reg_1777_pp0_iter5_reg <= icmp_ln78_1_reg_1777_pp0_iter4_reg;
        icmp_ln78_1_reg_1777_pp0_iter6_reg <= icmp_ln78_1_reg_1777_pp0_iter5_reg;
        icmp_ln78_1_reg_1777_pp0_iter7_reg <= icmp_ln78_1_reg_1777_pp0_iter6_reg;
        icmp_ln78_1_reg_1777_pp0_iter8_reg <= icmp_ln78_1_reg_1777_pp0_iter7_reg;
        icmp_ln78_1_reg_1777_pp0_iter9_reg <= icmp_ln78_1_reg_1777_pp0_iter8_reg;
        icmp_ln79_1_reg_1871 <= icmp_ln79_1_fu_1066_p2;
        icmp_ln79_2_reg_1773 <= icmp_ln79_2_fu_710_p2;
        icmp_ln79_2_reg_1773_pp0_iter10_reg <= icmp_ln79_2_reg_1773_pp0_iter9_reg;
        icmp_ln79_2_reg_1773_pp0_iter11_reg <= icmp_ln79_2_reg_1773_pp0_iter10_reg;
        icmp_ln79_2_reg_1773_pp0_iter12_reg <= icmp_ln79_2_reg_1773_pp0_iter11_reg;
        icmp_ln79_2_reg_1773_pp0_iter13_reg <= icmp_ln79_2_reg_1773_pp0_iter12_reg;
        icmp_ln79_2_reg_1773_pp0_iter14_reg <= icmp_ln79_2_reg_1773_pp0_iter13_reg;
        icmp_ln79_2_reg_1773_pp0_iter15_reg <= icmp_ln79_2_reg_1773_pp0_iter14_reg;
        icmp_ln79_2_reg_1773_pp0_iter16_reg <= icmp_ln79_2_reg_1773_pp0_iter15_reg;
        icmp_ln79_2_reg_1773_pp0_iter17_reg <= icmp_ln79_2_reg_1773_pp0_iter16_reg;
        icmp_ln79_2_reg_1773_pp0_iter18_reg <= icmp_ln79_2_reg_1773_pp0_iter17_reg;
        icmp_ln79_2_reg_1773_pp0_iter19_reg <= icmp_ln79_2_reg_1773_pp0_iter18_reg;
        icmp_ln79_2_reg_1773_pp0_iter20_reg <= icmp_ln79_2_reg_1773_pp0_iter19_reg;
        icmp_ln79_2_reg_1773_pp0_iter21_reg <= icmp_ln79_2_reg_1773_pp0_iter20_reg;
        icmp_ln79_2_reg_1773_pp0_iter4_reg <= icmp_ln79_2_reg_1773;
        icmp_ln79_2_reg_1773_pp0_iter5_reg <= icmp_ln79_2_reg_1773_pp0_iter4_reg;
        icmp_ln79_2_reg_1773_pp0_iter6_reg <= icmp_ln79_2_reg_1773_pp0_iter5_reg;
        icmp_ln79_2_reg_1773_pp0_iter7_reg <= icmp_ln79_2_reg_1773_pp0_iter6_reg;
        icmp_ln79_2_reg_1773_pp0_iter8_reg <= icmp_ln79_2_reg_1773_pp0_iter7_reg;
        icmp_ln79_2_reg_1773_pp0_iter9_reg <= icmp_ln79_2_reg_1773_pp0_iter8_reg;
        icmp_ln79_mid258_reg_1741 <= icmp_ln79_mid258_fu_654_p2;
        icmp_ln79_mid258_reg_1741_pp0_iter4_reg <= icmp_ln79_mid258_reg_1741;
        icmp_ln79_mid258_reg_1741_pp0_iter5_reg <= icmp_ln79_mid258_reg_1741_pp0_iter4_reg;
        icmp_ln79_mid258_reg_1741_pp0_iter6_reg <= icmp_ln79_mid258_reg_1741_pp0_iter5_reg;
        icmp_ln79_mid258_reg_1741_pp0_iter7_reg <= icmp_ln79_mid258_reg_1741_pp0_iter6_reg;
        icmp_ln84_reg_1810 <= icmp_ln84_fu_910_p2;
        kx_mid2_reg_1759 <= kx_mid2_fu_688_p3;
        kx_mid2_reg_1759_pp0_iter4_reg <= kx_mid2_reg_1759;
        kx_mid2_reg_1759_pp0_iter5_reg <= kx_mid2_reg_1759_pp0_iter4_reg;
        kx_mid2_reg_1759_pp0_iter6_reg <= kx_mid2_reg_1759_pp0_iter5_reg;
        not_exitcond_flatten61_mid2127_reg_1683 <= not_exitcond_flatten61_mid2127_fu_485_p2;
        not_exitcond_flatten90_mid2178249_reg_1644_pp0_iter2_reg <= not_exitcond_flatten90_mid2178249_reg_1644;
        or_ln17_reg_1932 <= or_ln17_fu_1369_p2;
        select_ln18_reg_1927 <= select_ln18_fu_1356_p3;
        select_ln71_1_reg_1716 <= select_ln71_1_fu_594_p3;
        select_ln71_1_reg_1716_pp0_iter4_reg <= select_ln71_1_reg_1716;
        select_ln71_1_reg_1716_pp0_iter5_reg <= select_ln71_1_reg_1716_pp0_iter4_reg;
        select_ln71_1_reg_1716_pp0_iter6_reg <= select_ln71_1_reg_1716_pp0_iter5_reg;
        select_ln72_reg_1730 <= select_ln72_fu_612_p3;
        select_ln72_reg_1730_pp0_iter4_reg <= select_ln72_reg_1730;
        select_ln72_reg_1730_pp0_iter5_reg <= select_ln72_reg_1730_pp0_iter4_reg;
        select_ln72_reg_1730_pp0_iter6_reg <= select_ln72_reg_1730_pp0_iter5_reg;
        select_ln72_reg_1730_pp0_iter7_reg <= select_ln72_reg_1730_pp0_iter6_reg;
        select_ln73_reg_1795 <= select_ln73_fu_775_p3;
        select_ln73_reg_1795_pp0_iter5_reg <= select_ln73_reg_1795;
        select_ln73_reg_1795_pp0_iter6_reg <= select_ln73_reg_1795_pp0_iter5_reg;
        select_ln73_reg_1795_pp0_iter7_reg <= select_ln73_reg_1795_pp0_iter6_reg;
        select_ln77_reg_1746 <= select_ln77_fu_660_p3;
        select_ln78_reg_1766 <= select_ln78_fu_696_p3;
        sub_ln94_reg_1861[9 : 2] <= sub_ln94_fu_1060_p2[9 : 2];
        tmp_10_reg_1922 <= add_ln317_fu_1332_p2[32'd8];
        tmp_7_reg_1938 <= grp_fu_183_p_dout0;
        tmp_8_reg_1943 <= grp_fu_263_p2;
        trunc_ln17_reg_1911 <= trunc_ln17_fu_1310_p1;
        trunc_ln85_reg_1805 <= trunc_ln85_fu_893_p1;
        val_1_reg_1948 <= val_1_fu_1426_p3;
        val_reg_1899 <= grp_fu_179_p_dout0;
        xor_ln71_reg_1622_pp0_iter2_reg <= xor_ln71_reg_1622;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln77_1_reg_1668 <= add_ln77_1_fu_418_p2;
        and_ln71_3_reg_1628 <= and_ln71_3_fu_376_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_19_reg_1662 <= empty_19_fu_412_p2;
        empty_reg_1638 <= empty_fu_382_p2;
        exitcond_flatten61_mid2127_reg_1650 <= exitcond_flatten61_mid2127_fu_406_p2;
        icmp_ln71_reg_1606 <= icmp_ln71_fu_326_p2;
        icmp_ln71_reg_1606_pp0_iter1_reg <= icmp_ln71_reg_1606;
        icmp_ln72_reg_1610 <= icmp_ln72_fu_352_p2;
        not_exitcond_flatten90_mid2178249_reg_1644 <= not_exitcond_flatten90_mid2178249_fu_394_p2;
        xor_ln71_reg_1622 <= xor_ln71_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln79_2_fu_1202_p2 == 1'd0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        sext_ln8910_fu_194 <= select_ln72_1_fu_1212_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        sum_3_reg_1889 <= grp_fu_1505_p3;
    end
end

always @ (*) begin
    if (((icmp_ln71_fu_326_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln71_reg_1606_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter21_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten179_load = 20'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten179_load = indvar_flatten179_fu_190;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln71_reg_1606_pp0_iter1_reg == 1'd0))) begin
        ap_sig_allocacmp_indvar_flatten59_load = select_ln77_1_fu_520_p3;
    end else begin
        ap_sig_allocacmp_indvar_flatten59_load = indvar_flatten59_fu_166;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ap_sig_allocacmp_sum_load = grp_fu_1505_p3;
    end else begin
        ap_sig_allocacmp_sum_load = sum_fu_146;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((or_ln79_2_fu_1202_p2 == 1'd1) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
            ap_sig_allocacmp_sum_load_1 = sum_11_mid275_fu_1127_p3;
        end else if (((or_ln79_2_fu_1202_p2 == 1'd0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
            ap_sig_allocacmp_sum_load_1 = select_ln72_2_fu_1220_p3;
        end else if ((ap_enable_reg_pp0_iter9 == 1'b1)) begin
            ap_sig_allocacmp_sum_load_1 = grp_fu_1505_p3;
        end else begin
            ap_sig_allocacmp_sum_load_1 = sum_fu_146;
        end
    end else begin
        ap_sig_allocacmp_sum_load_1 = sum_fu_146;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        conv2_b_ce0_local = 1'b1;
    end else begin
        conv2_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        conv2_w_ce0_local = 1'b1;
    end else begin
        conv2_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        layer1_out_ce0_local = 1'b1;
    end else begin
        layer1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter22 == 1'b1))) begin
        layer2_out_ce0_local = 1'b1;
    end else begin
        layer2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter22 == 1'b1) & (icmp_ln77_1_reg_1781_pp0_iter21_reg == 1'd1) & (icmp_ln78_1_reg_1777_pp0_iter21_reg == 1'd1) & (icmp_ln79_2_reg_1773_pp0_iter21_reg == 1'd1))) begin
        layer2_out_we0_local = 1'b1;
    end else begin
        layer2_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln317_fu_1332_p2 = ($signed(zext_ln317_fu_1328_p1) + $signed(9'd385));

assign add_ln71_1_fu_332_p2 = (ap_sig_allocacmp_indvar_flatten179_load + 20'd1);

assign add_ln71_fu_552_p2 = (oc_fu_186 + 5'd1);

assign add_ln72_1_fu_438_p2 = (indvar_flatten128_fu_182 + 16'd1);

assign add_ln72_2_fu_800_p2 = (p_shl1_fu_782_p3 + zext_ln72_fu_796_p1);

assign add_ln72_fu_601_p2 = (select_ln71_fu_558_p3 + 5'd1);

assign add_ln73_1_fu_424_p2 = (indvar_flatten88_fu_174 + 12'd1);

assign add_ln73_fu_769_p2 = (x_1_mid296_fu_762_p3 + 5'd1);

assign add_ln77_1_fu_418_p2 = (ap_sig_allocacmp_indvar_flatten59_load + 8'd1);

assign add_ln77_fu_626_p2 = (ic_mid267_fu_619_p3 + 4'd1);

assign add_ln78_1_fu_506_p2 = (indvar_flatten42_fu_158 + 4'd1);

assign add_ln78_fu_667_p2 = (ky_mid250_fu_632_p3 + 2'd1);

assign add_ln79_fu_704_p2 = (kx_mid2_fu_688_p3 + 2'd1);

assign add_ln80_1_fu_877_p2 = ($signed(sext_ln80_fu_873_p1) + $signed(zext_ln72_1_fu_806_p1));

assign add_ln80_fu_868_p2 = ($signed(select_ln78_reg_1766) + $signed(2'd3));

assign add_ln81_1_fu_928_p2 = ($signed(sext_ln81_fu_924_p1) + $signed(zext_ln73_fu_809_p1));

assign add_ln81_fu_919_p2 = ($signed(kx_mid2_reg_1759) + $signed(2'd3));

assign add_ln85_1_fu_988_p2 = ($signed(sub_ln89_fu_979_p2) + $signed(sext_ln85_1_fu_985_p1));

assign add_ln85_fu_887_p2 = ($signed(zext_ln77_fu_837_p1) + $signed(sext_ln85_fu_883_p1));

assign add_ln89_1_fu_940_p2 = (sub_ln89_1_fu_904_p2 + zext_ln79_fu_916_p1);

assign add_ln89_2_fu_950_p2 = (zext_ln89_fu_946_p1 + add_ln89_fu_934_p2);

assign add_ln89_3_fu_855_p2 = (zext_ln89_1_fu_851_p1 + zext_ln77_1_fu_841_p1);

assign add_ln89_fu_934_p2 = (zext_ln78_fu_861_p1 + add_ln72_2_fu_800_p2);

assign add_ln94_1_fu_1287_p2 = (sub_ln72_fu_1278_p2 + zext_ln94_3_fu_1284_p1);

assign add_ln94_fu_1249_p2 = (sub_ln94_reg_1861 + zext_ln94_1_fu_1246_p1);

assign and_ln17_fu_1437_p2 = (tmp_7_reg_1938 & or_ln17_reg_1932);

assign and_ln18_1_fu_1470_p2 = (xor_ln17_fu_1464_p2 & and_ln18_fu_1441_p2);

assign and_ln18_fu_1441_p2 = (tmp_8_reg_1943 & or_ln17_reg_1932);

assign and_ln71_1_fu_471_p2 = (xor_ln71_reg_1622 & icmp_ln78_fu_465_p2);

assign and_ln71_2_fu_400_p2 = (xor_ln71_fu_358_p2 & icmp_ln77_fu_364_p2);

assign and_ln71_3_fu_376_p2 = (xor_ln71_fu_358_p2 & icmp_ln73_fu_370_p2);

assign and_ln71_fu_589_p2 = (xor_ln71_reg_1622_pp0_iter2_reg & icmp_ln79_fu_583_p2);

assign and_ln84_fu_1004_p2 = (icmp_ln84_reg_1810 & icmp_ln84_1_fu_999_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv2_b_address0 = zext_ln71_fu_1038_p1;

assign conv2_w_address0 = zext_ln90_fu_1009_p1;

assign data_fu_1297_p1 = val_reg_1899;

assign empty_19_fu_412_p2 = (exitcond_flatten61_mid2127_fu_406_p2 | and_ln71_3_fu_376_p2);

assign empty_20_fu_481_p2 = (icmp_ln72_reg_1610 | empty_19_reg_1662);

assign empty_21_fu_496_p2 = (exitcond_flatten61_mid2127_reg_1650 | exitcond_flatten44_mid287_fu_490_p2);

assign empty_22_fu_501_p2 = (empty_reg_1638 | empty_21_fu_496_p2);

assign empty_23_fu_673_p2 = (exitcond_flatten44_mid287_reg_1688 | empty_19_reg_1662_pp0_iter2_reg);

assign empty_24_fu_677_p2 = (icmp_ln79_mid258_fu_654_p2 | empty_23_fu_673_p2);

assign empty_25_fu_683_p2 = (icmp_ln72_reg_1610_pp0_iter2_reg | empty_24_fu_677_p2);

assign empty_fu_382_p2 = (icmp_ln72_fu_352_p2 | and_ln71_3_fu_376_p2);

assign exitcond_flatten44_mid2123_fu_476_p2 = (not_exitcond_flatten90_mid2178249_reg_1644 & and_ln71_1_fu_471_p2);

assign exitcond_flatten44_mid2123_not_fu_639_p2 = (exitcond_flatten44_mid2123_reg_1673 ^ 1'd1);

assign exitcond_flatten44_mid287_fu_490_p2 = (not_exitcond_flatten61_mid2127_fu_485_p2 & exitcond_flatten44_mid2123_fu_476_p2);

assign exitcond_flatten61_mid2127_fu_406_p2 = (not_exitcond_flatten90_mid2178249_fu_394_p2 & and_ln71_2_fu_400_p2);

assign exitcond_flatten90_not250_fu_388_p2 = (icmp_ln73_fu_370_p2 ^ 1'd1);

assign first_iter_3288_fu_577_p2 = ((ky_fu_154 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_3_mid1_fu_1033_p2 = ((add_ln78_reg_1754_pp0_iter6_reg == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_3_mid2117_fu_1122_p2 = (or_ln71_3_fu_1089_p2 | and_ln71_3_reg_1628_pp0_iter7_reg);

assign first_iter_3_mid256_fu_1162_p2 = (first_iter_3_mid281_fu_1151_p2 | exitcond_flatten44_mid287_reg_1688_pp0_iter7_reg);

assign first_iter_3_mid281_fu_1151_p2 = (first_iter_3_mid2117_fu_1122_p2 | exitcond_flatten61_mid2127_reg_1650_pp0_iter7_reg);

assign first_iter_3_mid2_fu_1167_p3 = ((icmp_ln79_mid258_reg_1741_pp0_iter7_reg[0:0] == 1'b1) ? first_iter_3_mid1_reg_1856 : first_iter_3_mid256_fu_1162_p2);

assign first_iter_4286_fu_571_p2 = ((ic_fu_162 == 4'd0) ? 1'b1 : 1'b0);

assign first_iter_4_mid1_fu_1028_p2 = ((add_ln77_reg_1736_pp0_iter6_reg == 4'd0) ? 1'b1 : 1'b0);

assign first_iter_4_mid2113_fu_1117_p2 = (or_ln71_2_fu_1085_p2 | and_ln71_3_reg_1628_pp0_iter7_reg);

assign first_iter_4_mid277_fu_1146_p2 = (first_iter_4_mid2113_fu_1117_p2 | exitcond_flatten61_mid2127_reg_1650_pp0_iter7_reg);

assign first_iter_4_mid2_fu_1156_p3 = ((exitcond_flatten44_mid287_reg_1688_pp0_iter7_reg[0:0] == 1'b1) ? first_iter_4_mid1_reg_1851 : first_iter_4_mid277_fu_1146_p2);

assign first_iter_5284_fu_756_p2 = ((x_fu_170 == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_5_mid1_fu_1134_p2 = ((add_ln73_reg_1790_pp0_iter7_reg == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_5_mid2109_fu_1112_p2 = (or_ln71_1_fu_1081_p2 | and_ln71_3_reg_1628_pp0_iter7_reg);

assign first_iter_5_mid2_fu_1139_p3 = ((exitcond_flatten61_mid2127_reg_1650_pp0_iter7_reg[0:0] == 1'b1) ? first_iter_5_mid1_fu_1134_p2 : first_iter_5_mid2109_fu_1112_p2);

assign first_iter_6281_fu_565_p2 = ((y_fu_178 == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_6_mid1_fu_1100_p2 = ((add_ln72_reg_1725_pp0_iter7_reg == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_6_mid2_fu_1105_p3 = ((and_ln71_3_reg_1628_pp0_iter7_reg[0:0] == 1'b1) ? first_iter_6_mid1_fu_1100_p2 : or_ln71_fu_1077_p2);

assign grp_fu_179_p_ce = 1'b1;

assign grp_fu_179_p_din0 = conv_i1_reg_1894;

assign grp_fu_179_p_din1 = 32'd998397149;

assign grp_fu_183_p_ce = 1'b1;

assign grp_fu_183_p_din0 = val_reg_1899;

assign grp_fu_183_p_din1 = 32'd0;

assign grp_fu_183_p_opcode = 5'd4;

assign grp_fu_187_p_ce = 1'b1;

assign grp_fu_187_p_din0 = sum_3_reg_1889;

assign ic_mid267_fu_619_p3 = ((empty_20_reg_1678[0:0] == 1'b1) ? 4'd0 : ic_fu_162);

assign icmp_ln17_1_fu_1364_p2 = ((trunc_ln17_reg_1911 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_1314_p2 = ((tmp_s_fu_1300_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_326_p2 = ((ap_sig_allocacmp_indvar_flatten179_load == 20'd903168) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_352_p2 = ((indvar_flatten128_fu_182 == 16'd56448) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_370_p2 = ((indvar_flatten88_fu_174 == 12'd2016) ? 1'b1 : 1'b0);

assign icmp_ln77_1_fu_722_p2 = ((select_ln77_fu_660_p3 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_364_p2 = ((ap_sig_allocacmp_indvar_flatten59_load == 8'd72) ? 1'b1 : 1'b0);

assign icmp_ln78_1_fu_716_p2 = ((select_ln78_fu_696_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln78_fu_465_p2 = ((indvar_flatten42_fu_158 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln79_1_fu_1066_p2 = ((kx_mid2_reg_1759_pp0_iter6_reg != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln79_2_fu_710_p2 = ((add_ln79_fu_704_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_583_p2 = ((kx_fu_150 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln79_mid2119_fu_607_p2 = (not_exitcond_flatten90_mid2178249_reg_1644_pp0_iter2_reg & and_ln71_fu_589_p2);

assign icmp_ln79_mid258_fu_654_p2 = (not_exitcond_flatten44_mid287_fu_644_p2 & icmp_ln79_mid283_fu_649_p2);

assign icmp_ln79_mid283_fu_649_p2 = (not_exitcond_flatten61_mid2127_reg_1683 & icmp_ln79_mid2119_fu_607_p2);

assign icmp_ln84_1_fu_999_p2 = ((add_ln81_1_reg_1815 < 6'd28) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_910_p2 = ((add_ln80_1_fu_877_p2 < 6'd28) ? 1'b1 : 1'b0);

assign kx_mid2_fu_688_p3 = ((empty_25_fu_683_p2[0:0] == 1'b1) ? 2'd0 : kx_fu_150);

assign ky_mid250_fu_632_p3 = ((empty_22_reg_1696[0:0] == 1'b1) ? 2'd0 : ky_fu_154);

assign layer1_out_address0 = zext_ln85_1_fu_994_p1;

assign layer1_out_ce0 = layer1_out_ce0_local;

assign layer2_out_address0 = zext_ln94_4_fu_1433_p1;

assign layer2_out_ce0 = layer2_out_ce0_local;

assign layer2_out_d0 = retval_0_i1_fu_1484_p9;

assign layer2_out_we0 = layer2_out_we0_local;

assign lshr_ln18_fu_1394_p2 = zext_ln15_fu_1383_p1 >> zext_ln18_fu_1390_p1;

assign mantissa_fu_1374_p4 = {{{{1'd1}, {trunc_ln17_reg_1911}}}, {1'd0}};

assign not_exitcond_flatten44_mid287_fu_644_p2 = (exitcond_flatten61_mid2127_reg_1650_pp0_iter2_reg | exitcond_flatten44_mid2123_not_fu_639_p2);

assign not_exitcond_flatten61_mid2127_fu_485_p2 = (exitcond_flatten61_mid2127_reg_1650 ^ 1'd1);

assign not_exitcond_flatten90_mid2178249_fu_394_p2 = (icmp_ln72_fu_352_p2 | exitcond_flatten90_not250_fu_388_p2);

assign or_ln17_fu_1369_p2 = (icmp_ln17_reg_1917 | icmp_ln17_1_fu_1364_p2);

assign or_ln71_1_fu_1081_p2 = (icmp_ln72_reg_1610_pp0_iter7_reg | first_iter_5284_reg_1785_pp0_iter7_reg);

assign or_ln71_2_fu_1085_p2 = (icmp_ln72_reg_1610_pp0_iter7_reg | first_iter_4286_reg_1706_pp0_iter7_reg);

assign or_ln71_3_fu_1089_p2 = (icmp_ln72_reg_1610_pp0_iter7_reg | first_iter_3288_reg_1711_pp0_iter7_reg);

assign or_ln71_fu_1077_p2 = (icmp_ln72_reg_1610_pp0_iter7_reg | first_iter_6281_reg_1701_pp0_iter7_reg);

assign or_ln79_1_fu_1190_p2 = (xor_ln79_1_fu_1184_p2 | or_ln79_fu_1179_p2);

assign or_ln79_2_fu_1202_p2 = (xor_ln79_2_fu_1196_p2 | or_ln79_1_fu_1190_p2);

assign or_ln79_fu_1179_p2 = (xor_ln79_fu_1173_p2 | icmp_ln79_1_reg_1871);

assign p_shl1_fu_782_p3 = {{select_ln71_1_reg_1716}, {6'd0}};

assign p_shl2_fu_813_p3 = {{select_ln77_reg_1746}, {5'd0}};

assign p_shl3_fu_961_p3 = {{trunc_ln85_reg_1805}, {5'd0}};

assign p_shl4_fu_897_p3 = {{select_ln78_reg_1766}, {2'd0}};

assign p_shl_fu_1042_p3 = {{select_ln71_1_reg_1716_pp0_iter6_reg}, {5'd0}};

assign retval_0_i1_fu_1484_p6 = ((xs_sign_fu_1445_p3[0:0] == 1'b1) ? sub_ln59_fu_1452_p2 : val_1_reg_1948);

assign retval_0_i1_fu_1484_p7 = 'bx;

assign retval_0_i1_fu_1484_p8 = {{and_ln17_fu_1437_p2}, {and_ln18_1_fu_1470_p2}};

assign select_ln18_fu_1356_p3 = ((tmp_10_fu_1338_p3[0:0] == 1'b1) ? sext_ln18_fu_1352_p1 : add_ln317_fu_1332_p2);

assign select_ln71_1_fu_594_p3 = ((icmp_ln72_reg_1610_pp0_iter2_reg[0:0] == 1'b1) ? add_ln71_fu_552_p2 : oc_fu_186);

assign select_ln71_fu_558_p3 = ((icmp_ln72_reg_1610_pp0_iter2_reg[0:0] == 1'b1) ? 5'd0 : y_fu_178);

assign select_ln72_1_fu_1212_p3 = ((first_iter_6_mid2_fu_1105_p3[0:0] == 1'b1) ? sext_ln89_fu_1208_p1 : sext_ln8910_fu_194);

assign select_ln72_2_fu_1220_p3 = ((first_iter_6_mid2_fu_1105_p3[0:0] == 1'b1) ? sext_ln89_fu_1208_p1 : sum_11_mid275_fu_1127_p3);

assign select_ln72_3_fu_444_p3 = ((icmp_ln72_fu_352_p2[0:0] == 1'b1) ? 16'd1 : add_ln72_1_fu_438_p2);

assign select_ln72_fu_612_p3 = ((and_ln71_3_reg_1628_pp0_iter2_reg[0:0] == 1'b1) ? add_ln72_fu_601_p2 : select_ln71_fu_558_p3);

assign select_ln73_1_fu_430_p3 = ((empty_fu_382_p2[0:0] == 1'b1) ? 12'd1 : add_ln73_1_fu_424_p2);

assign select_ln73_fu_775_p3 = ((exitcond_flatten61_mid2127_reg_1650_pp0_iter3_reg[0:0] == 1'b1) ? add_ln73_fu_769_p2 : x_1_mid296_fu_762_p3);

assign select_ln77_1_fu_520_p3 = ((empty_20_fu_481_p2[0:0] == 1'b1) ? 8'd1 : add_ln77_1_reg_1668);

assign select_ln77_fu_660_p3 = ((exitcond_flatten44_mid287_reg_1688[0:0] == 1'b1) ? add_ln77_fu_626_p2 : ic_mid267_fu_619_p3);

assign select_ln78_1_fu_512_p3 = ((empty_22_fu_501_p2[0:0] == 1'b1) ? 4'd1 : add_ln78_1_fu_506_p2);

assign select_ln78_fu_696_p3 = ((icmp_ln79_mid258_fu_654_p2[0:0] == 1'b1) ? add_ln78_fu_667_p2 : ky_mid250_fu_632_p3);

assign sext_ln18_1_fu_1387_p1 = $signed(select_ln18_reg_1927);

assign sext_ln18_fu_1352_p1 = $signed(sub_ln18_fu_1346_p2);

assign sext_ln80_fu_873_p1 = $signed(add_ln80_fu_868_p2);

assign sext_ln81_fu_924_p1 = $signed(add_ln81_fu_919_p2);

assign sext_ln85_1_fu_985_p1 = add_ln81_1_reg_1815;

assign sext_ln85_fu_883_p1 = add_ln80_1_fu_877_p2;

assign sext_ln89_1_fu_975_p1 = $signed(tmp_6_fu_968_p3);

assign sext_ln89_fu_1208_p1 = $signed(conv2_b_q0);

assign shl_ln18_fu_1400_p2 = zext_ln15_fu_1383_p1 << zext_ln18_fu_1390_p1;

assign sub_ln18_fu_1346_p2 = (8'd127 - xs_exp_fu_1320_p3);

assign sub_ln59_fu_1452_p2 = (8'd0 - val_1_reg_1948);

assign sub_ln72_fu_1278_p2 = (tmp_3_fu_1266_p3 - zext_ln94_2_fu_1274_p1);

assign sub_ln85_fu_831_p2 = (p_shl2_fu_813_p3 - zext_ln85_fu_827_p1);

assign sub_ln89_1_fu_904_p2 = (p_shl4_fu_897_p3 - zext_ln78_1_fu_865_p1);

assign sub_ln89_fu_979_p2 = ($signed(p_shl3_fu_961_p3) - $signed(sext_ln89_1_fu_975_p1));

assign sub_ln94_fu_1060_p2 = (p_shl_fu_1042_p3 - zext_ln94_fu_1056_p1);

assign sum_11_mid2107_fu_1093_p3 = ((and_ln71_3_reg_1628_pp0_iter7_reg[0:0] == 1'b1) ? sext_ln8910_fu_194 : ap_sig_allocacmp_sum_load);

assign sum_11_mid275_fu_1127_p3 = ((exitcond_flatten61_mid2127_reg_1650_pp0_iter7_reg[0:0] == 1'b1) ? sext_ln8910_fu_194 : sum_11_mid2107_fu_1093_p3);

assign tmp_10_fu_1338_p3 = add_ln317_fu_1332_p2[32'd8];

assign tmp_11_fu_1416_p4 = {{shl_ln18_fu_1400_p2[31:24]}};

assign tmp_1_fu_789_p3 = {{select_ln71_1_reg_1716}, {3'd0}};

assign tmp_2_fu_1258_p3 = {{add_ln94_fu_1249_p2}, {2'd0}};

assign tmp_3_fu_1266_p3 = {{trunc_ln94_fu_1254_p1}, {5'd0}};

assign tmp_4_fu_820_p3 = {{select_ln77_reg_1746}, {2'd0}};

assign tmp_5_fu_844_p3 = {{select_ln77_reg_1746}, {3'd0}};

assign tmp_6_fu_968_p3 = {{add_ln85_reg_1800}, {2'd0}};

assign tmp_9_fu_1406_p4 = {{lshr_ln18_fu_1394_p2[31:24]}};

assign tmp_fu_1049_p3 = {{select_ln71_1_reg_1716_pp0_iter6_reg}, {2'd0}};

assign tmp_s_fu_1300_p4 = {{data_fu_1297_p1[30:23]}};

assign trunc_ln17_fu_1310_p1 = data_fu_1297_p1[22:0];

assign trunc_ln85_fu_893_p1 = add_ln85_fu_887_p2[7:0];

assign trunc_ln94_fu_1254_p1 = add_ln94_fu_1249_p2[8:0];

assign val_1_fu_1426_p3 = ((tmp_10_reg_1922[0:0] == 1'b1) ? tmp_9_fu_1406_p4 : tmp_11_fu_1416_p4);

assign val_in_1_fu_1013_p3 = ((and_ln84_reg_1831[0:0] == 1'b1) ? layer1_out_q0 : 8'd0);

assign x_1_mid296_fu_762_p3 = ((empty_reg_1638_pp0_iter3_reg[0:0] == 1'b1) ? 5'd0 : x_fu_170);

assign xor_ln17_fu_1464_p2 = (1'd1 ^ and_ln17_fu_1437_p2);

assign xor_ln71_fu_358_p2 = (icmp_ln72_fu_352_p2 ^ 1'd1);

assign xor_ln79_1_fu_1184_p2 = (first_iter_4_mid2_fu_1156_p3 ^ 1'd1);

assign xor_ln79_2_fu_1196_p2 = (first_iter_5_mid2_fu_1139_p3 ^ 1'd1);

assign xor_ln79_fu_1173_p2 = (first_iter_3_mid2_fu_1167_p3 ^ 1'd1);

assign xs_exp_fu_1320_p3 = {{data_fu_1297_p1[30:23]}};

assign xs_sign_fu_1445_p3 = data_reg_1906_pp0_iter21_reg[32'd31];

assign zext_ln15_fu_1383_p1 = mantissa_fu_1374_p4;

assign zext_ln18_fu_1390_p1 = $unsigned(sext_ln18_1_fu_1387_p1);

assign zext_ln317_fu_1328_p1 = xs_exp_fu_1320_p3;

assign zext_ln71_fu_1038_p1 = select_ln71_1_reg_1716_pp0_iter6_reg;

assign zext_ln72_1_fu_806_p1 = select_ln72_reg_1730;

assign zext_ln72_fu_796_p1 = tmp_1_fu_789_p3;

assign zext_ln73_fu_809_p1 = select_ln73_fu_775_p3;

assign zext_ln77_1_fu_841_p1 = select_ln77_reg_1746;

assign zext_ln77_fu_837_p1 = sub_ln85_fu_831_p2;

assign zext_ln78_1_fu_865_p1 = select_ln78_reg_1766;

assign zext_ln78_fu_861_p1 = add_ln89_3_fu_855_p2;

assign zext_ln79_fu_916_p1 = kx_mid2_reg_1759;

assign zext_ln85_1_fu_994_p1 = add_ln85_1_fu_988_p2;

assign zext_ln85_fu_827_p1 = tmp_4_fu_820_p3;

assign zext_ln89_1_fu_851_p1 = tmp_5_fu_844_p3;

assign zext_ln89_fu_946_p1 = add_ln89_1_fu_940_p2;

assign zext_ln90_fu_1009_p1 = add_ln89_2_reg_1821;

assign zext_ln94_1_fu_1246_p1 = select_ln72_reg_1730_pp0_iter7_reg;

assign zext_ln94_2_fu_1274_p1 = tmp_2_fu_1258_p3;

assign zext_ln94_3_fu_1284_p1 = select_ln73_reg_1795_pp0_iter7_reg;

assign zext_ln94_4_fu_1433_p1 = add_ln94_1_reg_1884_pp0_iter21_reg;

assign zext_ln94_fu_1056_p1 = tmp_fu_1049_p3;

always @ (posedge ap_clk) begin
    sub_ln94_reg_1861[1:0] <= 2'b00;
end

endmodule //dense_int8_dense_int8_Pipeline_VITIS_LOOP_71_6_VITIS_LOOP_72_7_VITIS_LOOP_73_8_VITIS_LOOP_7
