-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity dense_int8_dense_int8_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_VITIS_LOOP_38_3_conv1_w_Rcud is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of dense_int8_dense_int8_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_VITIS_LOOP_38_3_conv1_w_Rcud is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00011100", 1 => "11111101", 2 => "11101010", 3 => "11110101", 
    4 => "00110010", 5 => "11011100", 6 => "01100011", 7 => "01001011", 
    8 => "00000010", 9 => "10110100", 10 => "11100011", 11 => "01010110", 
    12 => "10101101", 13 => "00100101", 14 => "00010110", 15 => "11001101", 
    16 => "00101111", 17 => "01001101", 18 => "11110100", 19 => "00001111", 
    20 => "10010000", 21 => "01101111", 22 => "00110111", 23 => "00001011", 
    24 => "01011101", 25 => "11010110", 26 => "11011100", 27 => "10110110", 
    28 => "10000001", 29 => "10100000", 30 => "11100111", 31 => "00010001", 
    32 => "00010001", 33 => "00100101", 34 => "00101011", 35 => "00110111", 
    36 => "11101000", 37 => "00110100", 38 => "00111010", 39 => "00101000", 
    40 => "00110000", 41 => "01000011", 42 => "11001000", 43 => "00000111", 
    44 => "01000010", 45 => "00111010", 46 => "00010110", 47 => "00101111", 
    48 => "11000101", 49 => "00011100", 50 => "00100100", 51 => "00100110", 
    52 => "11101110", 53 => "00110100", 54 => "00001011", 55 => "00101010", 
    56 => "00110011", 57 => "11000100", 58 => "00000001", 59 => "11101111", 
    60 => "10100100", 61 => "00011000", 62 => "10110110", 63 => "00110000", 
    64 => "00101111", 65 => "11101110", 66 => "00010001", 67 => "00001100", 
    68 => "00011001", 69 => "11011110", 70 => "10110001", 71 => "10101111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

