-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITIS_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln103 : IN STD_LOGIC_VECTOR (61 downto 0);
    layer2_out_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    layer2_out_ce0 : OUT STD_LOGIC;
    layer2_out_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    grp_fu_187_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_187_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_187_p_ce : OUT STD_LOGIC );
end;


architecture behav of dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITIS_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv17_1EA00 : STD_LOGIC_VECTOR (16 downto 0) := "11110101000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv15_3100 : STD_LOGIC_VECTOR (14 downto 0) := "011000100000000";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv14_1C : STD_LOGIC_VECTOR (13 downto 0) := "00000000011100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv14_310 : STD_LOGIC_VECTOR (13 downto 0) := "00001100010000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv17_3100 : STD_LOGIC_VECTOR (16 downto 0) := "00011000100000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln110_2_reg_1044 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op190_write_state16 : BOOLEAN;
    signal ap_block_state16_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln103_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal fc_w_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal fc_w_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal fc_b_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal fc_b_q0 : STD_LOGIC_VECTOR (11 downto 0);
    signal gmem_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal icmp_ln103_reg_943 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln108_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_reg_947 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_reg_947_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln103_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln103_reg_959 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_reg_964 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln103_1_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln103_1_reg_969 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln103_1_reg_969_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln103_4_fu_327_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln103_4_reg_980 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln103_4_reg_980_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln103_4_reg_980_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln103_4_reg_980_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln103_4_reg_980_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_985 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_9_mid2_fu_456_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_9_mid2_reg_995 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_9_mid2_reg_995_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_9_mid2_reg_995_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_9_mid2_reg_995_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_9_mid2_reg_995_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_mid2205_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_mid2205_reg_1000 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln108_1_fu_484_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln108_1_reg_1006 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_2_mid2_fu_507_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_2_mid2_reg_1013 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_2_mid2_reg_1013_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln109_1_fu_529_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln109_1_reg_1019 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln110_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_reg_1025 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_reg_1025_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_reg_1025_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_reg_1025_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_reg_1025_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln112_fu_657_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln112_reg_1029 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln112_fu_663_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln112_reg_1034 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln110_2_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_reg_1044_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_1048_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_1052_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_839_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_7_reg_1086 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln122_fu_820_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln122_reg_1091 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln112_4_fu_773_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln114_fu_778_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln103_fu_790_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal x_fu_106 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln110_1_fu_677_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_x_load : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal flat_idx_1_fu_110 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal add_ln117_fu_671_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln108_119_fu_114 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal add_ln108_1_fu_699_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal flat_idx_fu_118 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal select_ln109_fu_623_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln11021_fu_122 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal add_ln110_fu_688_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal y_fu_126 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal indvar_flatten186_fu_130 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal select_ln109_2_fu_351_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal c_fu_134 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal indvars_iv136_fu_138 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal select_ln108_fu_609_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal indvar_flatten206_fu_142 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal select_ln108_3_fu_365_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal i_fu_146 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten238_fu_150 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal add_ln103_1_fu_277_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_sig_allocacmp_indvar_flatten238_load : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sum_5_fu_154 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln108_2_fu_801_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sum_5_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sum_5_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_out_ce0_local : STD_LOGIC;
    signal fc_w_ce0_local : STD_LOGIC;
    signal fc_b_ce0_local : STD_LOGIC;
    signal add_ln103_fu_297_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln109_1_fu_345_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln108_2_fu_359_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal first_iter_9303_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_8306_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln103_1_fu_397_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln108_fu_437_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal first_iter_9_mid1_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln103_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln103_1_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten188_not_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln103_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten188_mid2237_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_5_mid2195_fu_443_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_26_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_27_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln109_fu_491_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal first_iter_8_mid1_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_8_mid2203_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_8_mid2_fu_521_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_1_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln103_2_fu_581_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln103_3_fu_588_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln103_fu_574_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal flat_idx_1_mid2199_fu_602_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal flat_idx_mid2194_fu_595_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_637_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl_fu_630_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln112_fu_644_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln112_fu_648_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln112_1_fu_654_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal flat_idx_1_mid2_fu_616_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_62_fu_740_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_63_fu_747_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln112_2_fu_754_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln110_fu_758_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln112_3_fu_764_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln112_1_fu_767_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_830_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln104_fu_797_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_830_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_830_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_830_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_211_ce : STD_LOGIC;
    signal grp_fu_830_ce : STD_LOGIC;
    signal grp_fu_839_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_830_p10 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_830_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component dense_int8_sitofp_32s_32_6_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dense_int8_mac_muladd_14ns_4ns_14ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component dense_int8_mac_muladd_8s_8s_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITfYi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITg8j IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component dense_int8_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fc_w_U : component dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITfYi
    generic map (
        DataWidth => 8,
        AddressRange => 125440,
        AddressWidth => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fc_w_address0,
        ce0 => fc_w_ce0_local,
        q0 => fc_w_q0);

    fc_b_U : component dense_int8_dense_int8_Pipeline_VITIS_LOOP_103_12_VITIS_LOOP_108_13_VITIS_LOOP_109_14_VITg8j
    generic map (
        DataWidth => 12,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fc_b_address0,
        ce0 => fc_b_ce0_local,
        q0 => fc_b_q0);

    mac_muladd_14ns_4ns_14ns_17_4_1_U37 : component dense_int8_mac_muladd_14ns_4ns_14ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 14,
        din1_WIDTH => 4,
        din2_WIDTH => 14,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_830_p0,
        din1 => grp_fu_830_p1,
        din2 => grp_fu_830_p2,
        ce => grp_fu_830_ce,
        dout => grp_fu_830_p3);

    mac_muladd_8s_8s_32s_32_4_1_U38 : component dense_int8_mac_muladd_8s_8s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => fc_w_q0,
        din1 => layer2_out_q0,
        din2 => ap_sig_allocacmp_sum_5_load_1,
        ce => grp_fu_839_ce,
        dout => grp_fu_839_p3);

    flow_control_loop_pipe_sequential_init_U : component dense_int8_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter14_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    c_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    c_fu_134 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    c_fu_134 <= select_ln108_1_fu_484_p3;
                end if;
            end if; 
        end if;
    end process;

    flat_idx_1_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    flat_idx_1_fu_110 <= ap_const_lv14_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    flat_idx_1_fu_110 <= add_ln117_fu_671_p2;
                end if;
            end if; 
        end if;
    end process;

    flat_idx_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    flat_idx_fu_118 <= ap_const_lv14_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    flat_idx_fu_118 <= select_ln109_fu_623_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_146 <= ap_const_lv4_0;
                elsif (((icmp_ln103_reg_943 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_146 <= select_ln103_4_fu_327_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten186_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten186_fu_130 <= ap_const_lv10_0;
                elsif (((icmp_ln103_reg_943 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten186_fu_130 <= select_ln109_2_fu_351_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten206_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten206_fu_142 <= ap_const_lv15_0;
                elsif (((icmp_ln103_reg_943 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten206_fu_142 <= select_ln108_3_fu_365_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten238_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln103_fu_271_p2 = ap_const_lv1_0))) then 
                    indvar_flatten238_fu_150 <= add_ln103_1_fu_277_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten238_fu_150 <= ap_const_lv17_0;
                end if;
            end if; 
        end if;
    end process;

    indvars_iv136_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    indvars_iv136_fu_138 <= ap_const_lv14_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    indvars_iv136_fu_138 <= select_ln108_fu_609_p3;
                end if;
            end if; 
        end if;
    end process;

    sum_5_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln110_reg_1025_pp0_iter6_reg))) then 
                    sum_5_fu_154 <= select_ln108_2_fu_801_p3;
                elsif ((ap_enable_reg_pp0_iter8 = ap_const_logic_1)) then 
                    sum_5_fu_154 <= grp_fu_839_p3;
                end if;
            end if; 
        end if;
    end process;

    x_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    x_fu_106 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    x_fu_106 <= add_ln110_1_fu_677_p2;
                end if;
            end if; 
        end if;
    end process;

    y_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    y_fu_126 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    y_fu_126 <= select_ln109_1_fu_529_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                add_ln108_119_fu_114 <= add_ln108_1_fu_699_p2;
                add_ln11021_fu_122 <= add_ln110_fu_688_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln112_reg_1029 <= add_ln112_fu_657_p2;
                and_ln103_1_reg_969_pp0_iter2_reg <= and_ln103_1_reg_969;
                and_ln110_reg_1025 <= and_ln110_fu_543_p2;
                and_ln110_reg_1025_pp0_iter3_reg <= and_ln110_reg_1025;
                and_ln110_reg_1025_pp0_iter4_reg <= and_ln110_reg_1025_pp0_iter3_reg;
                and_ln110_reg_1025_pp0_iter5_reg <= and_ln110_reg_1025_pp0_iter4_reg;
                and_ln110_reg_1025_pp0_iter6_reg <= and_ln110_reg_1025_pp0_iter5_reg;
                bitcast_ln122_reg_1091 <= bitcast_ln122_fu_820_p1;
                first_iter_9_mid2_reg_995 <= first_iter_9_mid2_fu_456_p3;
                first_iter_9_mid2_reg_995_pp0_iter3_reg <= first_iter_9_mid2_reg_995;
                first_iter_9_mid2_reg_995_pp0_iter4_reg <= first_iter_9_mid2_reg_995_pp0_iter3_reg;
                first_iter_9_mid2_reg_995_pp0_iter5_reg <= first_iter_9_mid2_reg_995_pp0_iter4_reg;
                first_iter_9_mid2_reg_995_pp0_iter6_reg <= first_iter_9_mid2_reg_995_pp0_iter5_reg;
                icmp_ln108_1_reg_1052 <= icmp_ln108_1_fu_705_p2;
                icmp_ln108_1_reg_1052_pp0_iter10_reg <= icmp_ln108_1_reg_1052_pp0_iter9_reg;
                icmp_ln108_1_reg_1052_pp0_iter11_reg <= icmp_ln108_1_reg_1052_pp0_iter10_reg;
                icmp_ln108_1_reg_1052_pp0_iter12_reg <= icmp_ln108_1_reg_1052_pp0_iter11_reg;
                icmp_ln108_1_reg_1052_pp0_iter13_reg <= icmp_ln108_1_reg_1052_pp0_iter12_reg;
                icmp_ln108_1_reg_1052_pp0_iter14_reg <= icmp_ln108_1_reg_1052_pp0_iter13_reg;
                icmp_ln108_1_reg_1052_pp0_iter4_reg <= icmp_ln108_1_reg_1052;
                icmp_ln108_1_reg_1052_pp0_iter5_reg <= icmp_ln108_1_reg_1052_pp0_iter4_reg;
                icmp_ln108_1_reg_1052_pp0_iter6_reg <= icmp_ln108_1_reg_1052_pp0_iter5_reg;
                icmp_ln108_1_reg_1052_pp0_iter7_reg <= icmp_ln108_1_reg_1052_pp0_iter6_reg;
                icmp_ln108_1_reg_1052_pp0_iter8_reg <= icmp_ln108_1_reg_1052_pp0_iter7_reg;
                icmp_ln108_1_reg_1052_pp0_iter9_reg <= icmp_ln108_1_reg_1052_pp0_iter8_reg;
                icmp_ln108_reg_947_pp0_iter2_reg <= icmp_ln108_reg_947;
                icmp_ln109_1_reg_1048 <= icmp_ln109_1_fu_694_p2;
                icmp_ln109_1_reg_1048_pp0_iter10_reg <= icmp_ln109_1_reg_1048_pp0_iter9_reg;
                icmp_ln109_1_reg_1048_pp0_iter11_reg <= icmp_ln109_1_reg_1048_pp0_iter10_reg;
                icmp_ln109_1_reg_1048_pp0_iter12_reg <= icmp_ln109_1_reg_1048_pp0_iter11_reg;
                icmp_ln109_1_reg_1048_pp0_iter13_reg <= icmp_ln109_1_reg_1048_pp0_iter12_reg;
                icmp_ln109_1_reg_1048_pp0_iter14_reg <= icmp_ln109_1_reg_1048_pp0_iter13_reg;
                icmp_ln109_1_reg_1048_pp0_iter4_reg <= icmp_ln109_1_reg_1048;
                icmp_ln109_1_reg_1048_pp0_iter5_reg <= icmp_ln109_1_reg_1048_pp0_iter4_reg;
                icmp_ln109_1_reg_1048_pp0_iter6_reg <= icmp_ln109_1_reg_1048_pp0_iter5_reg;
                icmp_ln109_1_reg_1048_pp0_iter7_reg <= icmp_ln109_1_reg_1048_pp0_iter6_reg;
                icmp_ln109_1_reg_1048_pp0_iter8_reg <= icmp_ln109_1_reg_1048_pp0_iter7_reg;
                icmp_ln109_1_reg_1048_pp0_iter9_reg <= icmp_ln109_1_reg_1048_pp0_iter8_reg;
                icmp_ln110_2_reg_1044 <= icmp_ln110_2_fu_682_p2;
                icmp_ln110_2_reg_1044_pp0_iter10_reg <= icmp_ln110_2_reg_1044_pp0_iter9_reg;
                icmp_ln110_2_reg_1044_pp0_iter11_reg <= icmp_ln110_2_reg_1044_pp0_iter10_reg;
                icmp_ln110_2_reg_1044_pp0_iter12_reg <= icmp_ln110_2_reg_1044_pp0_iter11_reg;
                icmp_ln110_2_reg_1044_pp0_iter13_reg <= icmp_ln110_2_reg_1044_pp0_iter12_reg;
                icmp_ln110_2_reg_1044_pp0_iter14_reg <= icmp_ln110_2_reg_1044_pp0_iter13_reg;
                icmp_ln110_2_reg_1044_pp0_iter4_reg <= icmp_ln110_2_reg_1044;
                icmp_ln110_2_reg_1044_pp0_iter5_reg <= icmp_ln110_2_reg_1044_pp0_iter4_reg;
                icmp_ln110_2_reg_1044_pp0_iter6_reg <= icmp_ln110_2_reg_1044_pp0_iter5_reg;
                icmp_ln110_2_reg_1044_pp0_iter7_reg <= icmp_ln110_2_reg_1044_pp0_iter6_reg;
                icmp_ln110_2_reg_1044_pp0_iter8_reg <= icmp_ln110_2_reg_1044_pp0_iter7_reg;
                icmp_ln110_2_reg_1044_pp0_iter9_reg <= icmp_ln110_2_reg_1044_pp0_iter8_reg;
                icmp_ln110_mid2205_reg_1000 <= icmp_ln110_mid2205_fu_478_p2;
                select_ln103_4_reg_980_pp0_iter2_reg <= select_ln103_4_reg_980;
                select_ln103_4_reg_980_pp0_iter3_reg <= select_ln103_4_reg_980_pp0_iter2_reg;
                select_ln103_4_reg_980_pp0_iter4_reg <= select_ln103_4_reg_980_pp0_iter3_reg;
                select_ln103_4_reg_980_pp0_iter5_reg <= select_ln103_4_reg_980_pp0_iter4_reg;
                select_ln108_1_reg_1006 <= select_ln108_1_fu_484_p3;
                select_ln109_1_reg_1019 <= select_ln109_1_fu_529_p3;
                trunc_ln112_reg_1034 <= trunc_ln112_fu_663_p1;
                x_2_mid2_reg_1013 <= x_2_mid2_fu_507_p3;
                x_2_mid2_reg_1013_pp0_iter3_reg <= x_2_mid2_reg_1013;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                and_ln103_1_reg_969 <= and_ln103_1_fu_321_p2;
                empty_reg_985 <= empty_fu_335_p2;
                icmp_ln108_reg_947 <= icmp_ln108_fu_303_p2;
                icmp_ln109_reg_964 <= icmp_ln109_fu_315_p2;
                select_ln103_4_reg_980 <= select_ln103_4_fu_327_p3;
                xor_ln103_reg_959 <= xor_ln103_fu_309_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln103_reg_943 <= icmp_ln103_fu_271_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                sum_7_reg_1086 <= grp_fu_839_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln103_1_fu_277_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten238_load) + unsigned(ap_const_lv17_1));
    add_ln103_fu_297_p2 <= std_logic_vector(unsigned(i_fu_146) + unsigned(ap_const_lv4_1));
    add_ln108_1_fu_699_p2 <= std_logic_vector(unsigned(select_ln108_fu_609_p3) + unsigned(ap_const_lv14_310));
    add_ln108_2_fu_359_p2 <= std_logic_vector(unsigned(indvar_flatten206_fu_142) + unsigned(ap_const_lv15_1));
    add_ln108_fu_437_p2 <= std_logic_vector(unsigned(select_ln103_1_fu_397_p3) + unsigned(ap_const_lv5_1));
    add_ln109_1_fu_345_p2 <= std_logic_vector(unsigned(indvar_flatten186_fu_130) + unsigned(ap_const_lv10_1));
    add_ln109_fu_491_p2 <= std_logic_vector(unsigned(y_5_mid2195_fu_443_p3) + unsigned(ap_const_lv5_1));
    add_ln110_1_fu_677_p2 <= std_logic_vector(unsigned(x_2_mid2_reg_1013) + unsigned(ap_const_lv5_1));
    add_ln110_fu_688_p2 <= std_logic_vector(unsigned(select_ln109_fu_623_p3) + unsigned(ap_const_lv14_1C));
    add_ln112_1_fu_767_p2 <= std_logic_vector(unsigned(sub_ln110_fu_758_p2) + unsigned(zext_ln112_3_fu_764_p1));
    add_ln112_fu_657_p2 <= std_logic_vector(unsigned(sub_ln112_fu_648_p2) + unsigned(zext_ln112_1_fu_654_p1));
    add_ln117_fu_671_p2 <= std_logic_vector(unsigned(flat_idx_1_mid2_fu_616_p3) + unsigned(ap_const_lv14_1));
    and_ln103_1_fu_321_p2 <= (xor_ln103_fu_309_p2 and icmp_ln109_fu_315_p2);
    and_ln103_fu_432_p2 <= (xor_ln103_reg_959 and icmp_ln110_fu_426_p2);
    and_ln110_fu_543_p2 <= (icmp_ln110_1_fu_537_p2 and first_iter_8_mid2_fu_521_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_state16_io_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_io_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_state16_io_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_io_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_state16_io_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_io_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state16_io_grp1_assign_proc : process(m_axi_gmem_0_WREADY, ap_predicate_op190_write_state16)
    begin
                ap_block_state16_io_grp1 <= ((m_axi_gmem_0_WREADY = ap_const_logic_0) and (ap_predicate_op190_write_state16 = ap_const_boolean_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln103_fu_271_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln103_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln103_reg_943)
    begin
        if (((icmp_ln103_reg_943 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter14_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter14_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op190_write_state16_assign_proc : process(icmp_ln110_2_reg_1044_pp0_iter14_reg, icmp_ln109_1_reg_1048_pp0_iter14_reg, icmp_ln108_1_reg_1052_pp0_iter14_reg)
    begin
                ap_predicate_op190_write_state16 <= ((icmp_ln108_1_reg_1052_pp0_iter14_reg = ap_const_lv1_1) and (icmp_ln109_1_reg_1048_pp0_iter14_reg = ap_const_lv1_1) and (icmp_ln110_2_reg_1044_pp0_iter14_reg = ap_const_lv1_1));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten238_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten238_fu_150, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten238_load <= ap_const_lv17_0;
        else 
            ap_sig_allocacmp_indvar_flatten238_load <= indvar_flatten238_fu_150;
        end if; 
    end process;


    ap_sig_allocacmp_sum_5_load_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_grp1, grp_fu_839_p3, sum_5_fu_154)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            ap_sig_allocacmp_sum_5_load <= grp_fu_839_p3;
        else 
            ap_sig_allocacmp_sum_5_load <= sum_5_fu_154;
        end if; 
    end process;


    ap_sig_allocacmp_sum_5_load_1_assign_proc : process(ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_grp1, and_ln110_reg_1025_pp0_iter6_reg, grp_fu_839_p3, sum_5_fu_154, select_ln108_2_fu_801_p3)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) then
            if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln110_reg_1025_pp0_iter6_reg))) then 
                ap_sig_allocacmp_sum_5_load_1 <= select_ln108_2_fu_801_p3;
            elsif ((ap_enable_reg_pp0_iter8 = ap_const_logic_1)) then 
                ap_sig_allocacmp_sum_5_load_1 <= grp_fu_839_p3;
            else 
                ap_sig_allocacmp_sum_5_load_1 <= sum_5_fu_154;
            end if;
        else 
            ap_sig_allocacmp_sum_5_load_1 <= sum_5_fu_154;
        end if; 
    end process;


    ap_sig_allocacmp_x_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_grp1, x_fu_106, add_ln110_1_fu_677_p2)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            ap_sig_allocacmp_x_load <= add_ln110_1_fu_677_p2;
        else 
            ap_sig_allocacmp_x_load <= x_fu_106;
        end if; 
    end process;

    bitcast_ln122_fu_820_p1 <= grp_fu_187_p_dout0;
    empty_26_fu_497_p2 <= (icmp_ln110_mid2205_fu_478_p2 or and_ln103_1_reg_969);
    empty_27_fu_502_p2 <= (icmp_ln108_reg_947 or empty_26_fu_497_p2);
    empty_fu_335_p2 <= (icmp_ln108_fu_303_p2 or and_ln103_1_fu_321_p2);
    exitcond_flatten188_not_fu_468_p2 <= (icmp_ln109_reg_964 xor ap_const_lv1_1);
    fc_b_address0 <= zext_ln103_fu_790_p1(4 - 1 downto 0);

    fc_b_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            fc_b_ce0_local <= ap_const_logic_1;
        else 
            fc_b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fc_w_address0 <= zext_ln114_fu_778_p1(17 - 1 downto 0);

    fc_w_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            fc_w_ce0_local <= ap_const_logic_1;
        else 
            fc_w_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    first_iter_8306_fu_415_p2 <= "1" when (y_fu_126 = ap_const_lv5_0) else "0";
    first_iter_8_mid1_fu_515_p2 <= "1" when (add_ln109_fu_491_p2 = ap_const_lv5_0) else "0";
    first_iter_8_mid2203_fu_463_p2 <= (or_ln103_1_fu_421_p2 or and_ln103_1_reg_969);
    first_iter_8_mid2_fu_521_p3 <= 
        first_iter_8_mid1_fu_515_p2 when (icmp_ln110_mid2205_fu_478_p2(0) = '1') else 
        first_iter_8_mid2203_fu_463_p2;
    first_iter_9303_fu_404_p2 <= "1" when (c_fu_134 = ap_const_lv5_0) else "0";
    first_iter_9_mid1_fu_450_p2 <= "1" when (add_ln108_fu_437_p2 = ap_const_lv5_0) else "0";
    first_iter_9_mid2_fu_456_p3 <= 
        first_iter_9_mid1_fu_450_p2 when (and_ln103_1_reg_969(0) = '1') else 
        or_ln103_fu_410_p2;
    flat_idx_1_mid2199_fu_602_p3 <= 
        add_ln108_119_fu_114 when (and_ln103_1_reg_969_pp0_iter2_reg(0) = '1') else 
        select_ln103_3_fu_588_p3;
    flat_idx_1_mid2_fu_616_p3 <= 
        add_ln11021_fu_122 when (icmp_ln110_mid2205_reg_1000(0) = '1') else 
        flat_idx_1_mid2199_fu_602_p3;
    flat_idx_mid2194_fu_595_p3 <= 
        add_ln108_119_fu_114 when (and_ln103_1_reg_969_pp0_iter2_reg(0) = '1') else 
        select_ln103_2_fu_581_p3;

    gmem_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter15, m_axi_gmem_0_WREADY, ap_predicate_op190_write_state16, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op190_write_state16 = ap_const_boolean_1))) then 
            gmem_blk_n_W <= m_axi_gmem_0_WREADY;
        else 
            gmem_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_187_p_ce <= grp_fu_211_ce;
    grp_fu_187_p_din0 <= sum_7_reg_1086;

    grp_fu_211_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_211_ce <= ap_const_logic_1;
        else 
            grp_fu_211_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_830_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_830_ce <= ap_const_logic_1;
        else 
            grp_fu_830_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_830_p0 <= ap_const_lv17_3100(14 - 1 downto 0);
    grp_fu_830_p1 <= grp_fu_830_p10(4 - 1 downto 0);
    grp_fu_830_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln103_4_fu_327_p3),17));
    grp_fu_830_p2 <= grp_fu_830_p20(14 - 1 downto 0);
    grp_fu_830_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(flat_idx_1_mid2_fu_616_p3),17));

    grp_fu_839_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_839_ce <= ap_const_logic_1;
        else 
            grp_fu_839_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln103_fu_271_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten238_load = ap_const_lv17_1EA00) else "0";
    icmp_ln108_1_fu_705_p2 <= "1" when (select_ln108_1_reg_1006 = ap_const_lv5_F) else "0";
    icmp_ln108_fu_303_p2 <= "1" when (indvar_flatten206_fu_142 = ap_const_lv15_3100) else "0";
    icmp_ln109_1_fu_694_p2 <= "1" when (select_ln109_1_reg_1019 = ap_const_lv5_1B) else "0";
    icmp_ln109_fu_315_p2 <= "1" when (indvar_flatten186_fu_130 = ap_const_lv10_310) else "0";
    icmp_ln110_1_fu_537_p2 <= "1" when (x_2_mid2_fu_507_p3 = ap_const_lv5_0) else "0";
    icmp_ln110_2_fu_682_p2 <= "1" when (add_ln110_1_fu_677_p2 = ap_const_lv5_1C) else "0";
    icmp_ln110_fu_426_p2 <= "1" when (ap_sig_allocacmp_x_load = ap_const_lv5_1C) else "0";
    icmp_ln110_mid2205_fu_478_p2 <= (not_exitcond_flatten188_mid2237_fu_473_p2 and and_ln103_fu_432_p2);
    layer2_out_address0 <= zext_ln112_4_fu_773_p1(14 - 1 downto 0);
    layer2_out_ce0 <= layer2_out_ce0_local;

    layer2_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            layer2_out_ce0_local <= ap_const_logic_1;
        else 
            layer2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_0_BREADY <= ap_const_logic_0;
    m_axi_gmem_0_RREADY <= ap_const_logic_0;
    m_axi_gmem_0_WDATA <= bitcast_ln122_reg_1091;
    m_axi_gmem_0_WID <= ap_const_lv1_0;
    m_axi_gmem_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_0_WSTRB <= ap_const_lv4_F;
    m_axi_gmem_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter15, ap_predicate_op190_write_state16, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op190_write_state16 = ap_const_boolean_1))) then 
            m_axi_gmem_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    not_exitcond_flatten188_mid2237_fu_473_p2 <= (icmp_ln108_reg_947 or exitcond_flatten188_not_fu_468_p2);
    or_ln103_1_fu_421_p2 <= (icmp_ln108_reg_947 or first_iter_8306_fu_415_p2);
    or_ln103_fu_410_p2 <= (icmp_ln108_reg_947 or first_iter_9303_fu_404_p2);
    p_shl_fu_630_p3 <= (select_ln108_1_reg_1006 & ap_const_lv5_0);
    select_ln103_1_fu_397_p3 <= 
        ap_const_lv5_0 when (icmp_ln108_reg_947(0) = '1') else 
        c_fu_134;
    select_ln103_2_fu_581_p3 <= 
        ap_const_lv14_0 when (icmp_ln108_reg_947_pp0_iter2_reg(0) = '1') else 
        flat_idx_fu_118;
    select_ln103_3_fu_588_p3 <= 
        ap_const_lv14_0 when (icmp_ln108_reg_947_pp0_iter2_reg(0) = '1') else 
        flat_idx_1_fu_110;
    select_ln103_4_fu_327_p3 <= 
        add_ln103_fu_297_p2 when (icmp_ln108_fu_303_p2(0) = '1') else 
        i_fu_146;
    select_ln103_fu_574_p3 <= 
        ap_const_lv14_0 when (icmp_ln108_reg_947_pp0_iter2_reg(0) = '1') else 
        indvars_iv136_fu_138;
    select_ln108_1_fu_484_p3 <= 
        add_ln108_fu_437_p2 when (and_ln103_1_reg_969(0) = '1') else 
        select_ln103_1_fu_397_p3;
    select_ln108_2_fu_801_p3 <= 
        sext_ln104_fu_797_p1 when (first_iter_9_mid2_reg_995_pp0_iter6_reg(0) = '1') else 
        ap_sig_allocacmp_sum_5_load;
    select_ln108_3_fu_365_p3 <= 
        ap_const_lv15_1 when (icmp_ln108_fu_303_p2(0) = '1') else 
        add_ln108_2_fu_359_p2;
    select_ln108_fu_609_p3 <= 
        add_ln108_119_fu_114 when (and_ln103_1_reg_969_pp0_iter2_reg(0) = '1') else 
        select_ln103_fu_574_p3;
    select_ln109_1_fu_529_p3 <= 
        add_ln109_fu_491_p2 when (icmp_ln110_mid2205_fu_478_p2(0) = '1') else 
        y_5_mid2195_fu_443_p3;
    select_ln109_2_fu_351_p3 <= 
        ap_const_lv10_1 when (empty_fu_335_p2(0) = '1') else 
        add_ln109_1_fu_345_p2;
    select_ln109_fu_623_p3 <= 
        add_ln11021_fu_122 when (icmp_ln110_mid2205_reg_1000(0) = '1') else 
        flat_idx_mid2194_fu_595_p3;
        sext_ln104_fu_797_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(fc_b_q0),32));

    sub_ln110_fu_758_p2 <= std_logic_vector(unsigned(tmp_63_fu_747_p3) - unsigned(zext_ln112_2_fu_754_p1));
    sub_ln112_fu_648_p2 <= std_logic_vector(unsigned(p_shl_fu_630_p3) - unsigned(zext_ln112_fu_644_p1));
    tmp_62_fu_740_p3 <= (add_ln112_reg_1029 & ap_const_lv2_0);
    tmp_63_fu_747_p3 <= (trunc_ln112_reg_1034 & ap_const_lv5_0);
    tmp_fu_637_p3 <= (select_ln108_1_reg_1006 & ap_const_lv2_0);
    trunc_ln112_fu_663_p1 <= add_ln112_fu_657_p2(9 - 1 downto 0);
    x_2_mid2_fu_507_p3 <= 
        ap_const_lv5_0 when (empty_27_fu_502_p2(0) = '1') else 
        ap_sig_allocacmp_x_load;
    xor_ln103_fu_309_p2 <= (icmp_ln108_fu_303_p2 xor ap_const_lv1_1);
    y_5_mid2195_fu_443_p3 <= 
        ap_const_lv5_0 when (empty_reg_985(0) = '1') else 
        y_fu_126;
    zext_ln103_fu_790_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln103_4_reg_980_pp0_iter5_reg),64));
    zext_ln112_1_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln109_1_reg_1019),10));
    zext_ln112_2_fu_754_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_62_fu_740_p3),14));
    zext_ln112_3_fu_764_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_2_mid2_reg_1013_pp0_iter3_reg),14));
    zext_ln112_4_fu_773_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln112_1_fu_767_p2),64));
    zext_ln112_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_637_p3),10));
    zext_ln114_fu_778_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_830_p3),64));
end behav;
